/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type TraitWeightsStruct = {
  keys: PromiseOrValue<BigNumberish>[];
  weights: PromiseOrValue<BigNumberish>[];
};

export type TraitWeightsStructOutput = [BigNumber[], BigNumber[]] & {
  keys: BigNumber[];
  weights: BigNumber[];
};

export interface TraitHandlerInterface extends utils.Interface {
  functions: {
    "getTraitWeights()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getTraitWeights"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTraitWeights",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getTraitWeights",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TraitHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TraitHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getTraitWeights(
      overrides?: CallOverrides
    ): Promise<[TraitWeightsStructOutput[]]>;
  };

  getTraitWeights(
    overrides?: CallOverrides
  ): Promise<TraitWeightsStructOutput[]>;

  callStatic: {
    getTraitWeights(
      overrides?: CallOverrides
    ): Promise<TraitWeightsStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    getTraitWeights(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getTraitWeights(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
