/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type TraitStatsStruct = {
  health: BigNumberish;
  power: BigNumberish;
  violence: BigNumberish;
  harmony: BigNumberish;
  slots: BigNumberish;
};

export type TraitStatsStructOutput = [
  health: bigint,
  power: bigint,
  violence: bigint,
  harmony: bigint,
  slots: bigint
] & {
  health: bigint;
  power: bigint;
  violence: bigint;
  harmony: bigint;
  slots: bigint;
};

export interface TraitHandlerInterface extends Interface {
  getFunction(nameOrSignature: "_getTraitStats"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_getTraitStats",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_getTraitStats",
    data: BytesLike
  ): Result;
}

export interface TraitHandler extends BaseContract {
  connect(runner?: ContractRunner | null): TraitHandler;
  waitForDeployment(): Promise<this>;

  interface: TraitHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _getTraitStats: TypedContractMethod<
    [id: BigNumberish],
    [TraitStatsStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_getTraitStats"
  ): TypedContractMethod<[id: BigNumberish], [TraitStatsStructOutput], "view">;

  filters: {};
}
