/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface Uint256ArrayComponentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeWriter"
      | "cancelOwnershipHandover"
      | "completeOwnershipHandover"
      | "equal(uint256[],bytes)"
      | "equal(uint256,bytes)"
      | "extract(uint256[])"
      | "extract(uint256)"
      | "extractRaw(uint256[])"
      | "extractRaw(uint256)"
      | "get(uint256[])"
      | "get(uint256)"
      | "getAt"
      | "getEntitiesWithValue(uint256[])"
      | "getEntitiesWithValue(bytes)"
      | "getRaw(uint256[])"
      | "getRaw(uint256)"
      | "has"
      | "id"
      | "owner"
      | "ownershipHandoverExpiresAt"
      | "remove(uint256[])"
      | "remove(uint256)"
      | "renounceOwnership"
      | "requestOwnershipHandover"
      | "safeGet(uint256)"
      | "safeGet(uint256[])"
      | "set(uint256,bytes)"
      | "set(uint256,uint256[])"
      | "set(uint256[],bytes[])"
      | "set(uint256[],uint256[][])"
      | "size"
      | "transferOwnership"
      | "unauthorizeWriter"
      | "writeAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedWriter"
      | "OwnershipHandoverCanceled"
      | "OwnershipHandoverRequested"
      | "OwnershipTransferred"
      | "UnauthorizedWriter"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeWriter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeOwnershipHandover",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "equal(uint256[],bytes)",
    values: [BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "equal(uint256,bytes)",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extract(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "extract(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "extractRaw(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "extractRaw(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "get(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntitiesWithValue(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntitiesWithValue(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaw(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaw(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "has", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownershipHandoverExpiresAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remove(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "remove(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestOwnershipHandover",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeGet(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeGet(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "set(uint256,bytes)",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "set(uint256,uint256[])",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "set(uint256[],bytes[])",
    values: [BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "set(uint256[],uint256[][])",
    values: [BigNumberish[], BigNumberish[][]]
  ): string;
  encodeFunctionData(functionFragment: "size", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unauthorizeWriter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeAccess",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeWriter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "equal(uint256[],bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "equal(uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extract(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extract(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractRaw(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractRaw(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntitiesWithValue(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntitiesWithValue(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaw(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaw(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "has", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownershipHandoverExpiresAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestOwnershipHandover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeGet(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeGet(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set(uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set(uint256,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set(uint256[],bytes[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set(uint256[],uint256[][])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "size", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unauthorizeWriter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeAccess",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedWriterEvent {
  export type InputTuple = [writer: AddressLike];
  export type OutputTuple = [writer: string];
  export interface OutputObject {
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverCanceledEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverRequestedEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnauthorizedWriterEvent {
  export type InputTuple = [writer: AddressLike];
  export type OutputTuple = [writer: string];
  export interface OutputObject {
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Uint256ArrayComponent extends BaseContract {
  connect(runner?: ContractRunner | null): Uint256ArrayComponent;
  waitForDeployment(): Promise<this>;

  interface: Uint256ArrayComponentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeWriter: TypedContractMethod<
    [writer: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  completeOwnershipHandover: TypedContractMethod<
    [pendingOwner: AddressLike],
    [void],
    "payable"
  >;

  "equal(uint256[],bytes)": TypedContractMethod<
    [entities: BigNumberish[], value: BytesLike],
    [boolean],
    "view"
  >;

  "equal(uint256,bytes)": TypedContractMethod<
    [entity: BigNumberish, value: BytesLike],
    [boolean],
    "view"
  >;

  "extract(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [bigint[][]],
    "nonpayable"
  >;

  "extract(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [bigint[]],
    "nonpayable"
  >;

  "extractRaw(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [string[]],
    "nonpayable"
  >;

  "extractRaw(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [string],
    "nonpayable"
  >;

  "get(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [bigint[][]],
    "view"
  >;

  "get(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [bigint[]],
    "view"
  >;

  getAt: TypedContractMethod<
    [value: BytesLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  "getEntitiesWithValue(uint256[])": TypedContractMethod<
    [value: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  "getEntitiesWithValue(bytes)": TypedContractMethod<
    [value: BytesLike],
    [bigint[]],
    "view"
  >;

  "getRaw(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [string[]],
    "view"
  >;

  "getRaw(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [string],
    "view"
  >;

  has: TypedContractMethod<[entity: BigNumberish], [boolean], "view">;

  id: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownershipHandoverExpiresAt: TypedContractMethod<
    [pendingOwner: AddressLike],
    [bigint],
    "view"
  >;

  "remove(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  "remove(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "payable">;

  requestOwnershipHandover: TypedContractMethod<[], [void], "payable">;

  "safeGet(uint256)": TypedContractMethod<
    [entity: BigNumberish],
    [bigint[]],
    "view"
  >;

  "safeGet(uint256[])": TypedContractMethod<
    [entities: BigNumberish[]],
    [bigint[][]],
    "view"
  >;

  "set(uint256,bytes)": TypedContractMethod<
    [entity: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;

  "set(uint256,uint256[])": TypedContractMethod<
    [entity: BigNumberish, value: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  "set(uint256[],bytes[])": TypedContractMethod<
    [entities: BigNumberish[], values: BytesLike[]],
    [void],
    "nonpayable"
  >;

  "set(uint256[],uint256[][])": TypedContractMethod<
    [entities: BigNumberish[], values: BigNumberish[][]],
    [void],
    "nonpayable"
  >;

  size: TypedContractMethod<[value: BytesLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "payable"
  >;

  unauthorizeWriter: TypedContractMethod<
    [writer: AddressLike],
    [void],
    "nonpayable"
  >;

  writeAccess: TypedContractMethod<[operator: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeWriter"
  ): TypedContractMethod<[writer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "completeOwnershipHandover"
  ): TypedContractMethod<[pendingOwner: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "equal(uint256[],bytes)"
  ): TypedContractMethod<
    [entities: BigNumberish[], value: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "equal(uint256,bytes)"
  ): TypedContractMethod<
    [entity: BigNumberish, value: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "extract(uint256[])"
  ): TypedContractMethod<
    [entities: BigNumberish[]],
    [bigint[][]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "extract(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [bigint[]], "nonpayable">;
  getFunction(
    nameOrSignature: "extractRaw(uint256[])"
  ): TypedContractMethod<[entities: BigNumberish[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "extractRaw(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "get(uint256[])"
  ): TypedContractMethod<[entities: BigNumberish[]], [bigint[][]], "view">;
  getFunction(
    nameOrSignature: "get(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getAt"
  ): TypedContractMethod<
    [value: BytesLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntitiesWithValue(uint256[])"
  ): TypedContractMethod<[value: BigNumberish[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEntitiesWithValue(bytes)"
  ): TypedContractMethod<[value: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRaw(uint256[])"
  ): TypedContractMethod<[entities: BigNumberish[]], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRaw(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "has"
  ): TypedContractMethod<[entity: BigNumberish], [boolean], "view">;
  getFunction(nameOrSignature: "id"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownershipHandoverExpiresAt"
  ): TypedContractMethod<[pendingOwner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "remove(uint256[])"
  ): TypedContractMethod<[entities: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remove(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "requestOwnershipHandover"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "safeGet(uint256)"
  ): TypedContractMethod<[entity: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "safeGet(uint256[])"
  ): TypedContractMethod<[entities: BigNumberish[]], [bigint[][]], "view">;
  getFunction(
    nameOrSignature: "set(uint256,bytes)"
  ): TypedContractMethod<
    [entity: BigNumberish, value: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "set(uint256,uint256[])"
  ): TypedContractMethod<
    [entity: BigNumberish, value: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "set(uint256[],bytes[])"
  ): TypedContractMethod<
    [entities: BigNumberish[], values: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "set(uint256[],uint256[][])"
  ): TypedContractMethod<
    [entities: BigNumberish[], values: BigNumberish[][]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "size"
  ): TypedContractMethod<[value: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "unauthorizeWriter"
  ): TypedContractMethod<[writer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "writeAccess"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;

  getEvent(
    key: "AuthorizedWriter"
  ): TypedContractEvent<
    AuthorizedWriterEvent.InputTuple,
    AuthorizedWriterEvent.OutputTuple,
    AuthorizedWriterEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverCanceled"
  ): TypedContractEvent<
    OwnershipHandoverCanceledEvent.InputTuple,
    OwnershipHandoverCanceledEvent.OutputTuple,
    OwnershipHandoverCanceledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipHandoverRequested"
  ): TypedContractEvent<
    OwnershipHandoverRequestedEvent.InputTuple,
    OwnershipHandoverRequestedEvent.OutputTuple,
    OwnershipHandoverRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UnauthorizedWriter"
  ): TypedContractEvent<
    UnauthorizedWriterEvent.InputTuple,
    UnauthorizedWriterEvent.OutputTuple,
    UnauthorizedWriterEvent.OutputObject
  >;

  filters: {
    "AuthorizedWriter(address)": TypedContractEvent<
      AuthorizedWriterEvent.InputTuple,
      AuthorizedWriterEvent.OutputTuple,
      AuthorizedWriterEvent.OutputObject
    >;
    AuthorizedWriter: TypedContractEvent<
      AuthorizedWriterEvent.InputTuple,
      AuthorizedWriterEvent.OutputTuple,
      AuthorizedWriterEvent.OutputObject
    >;

    "OwnershipHandoverCanceled(address)": TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;
    OwnershipHandoverCanceled: TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;

    "OwnershipHandoverRequested(address)": TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;
    OwnershipHandoverRequested: TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UnauthorizedWriter(address)": TypedContractEvent<
      UnauthorizedWriterEvent.InputTuple,
      UnauthorizedWriterEvent.OutputTuple,
      UnauthorizedWriterEvent.OutputObject
    >;
    UnauthorizedWriter: TypedContractEvent<
      UnauthorizedWriterEvent.InputTuple,
      UnauthorizedWriterEvent.OutputTuple,
      UnauthorizedWriterEvent.OutputObject
    >;
  };
}
