// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

import "std-contracts/test/MudTest.t.sol";

// Libraries
import { LibAccount } from "libraries/LibAccount.sol";
import { LibCoin } from "libraries/LibCoin.sol";
import { LibInventory } from "libraries/LibInventory.sol";
import { LibInventoryNF } from "libraries/LibInventoryNF.sol";
import { LibListing } from "libraries/LibListing.sol";
import { LibMerchant } from "libraries/LibMerchant.sol";
import { LibModifier } from "libraries/LibModifier.sol";
import { LibNode } from "libraries/LibNode.sol";
import { LibPet } from "libraries/LibPet.sol";
import { LibProduction } from "libraries/LibProduction.sol";
import { LibPrototype } from "libraries/LibPrototype.sol";
import { LibRegister } from "libraries/LibRegister.sol";
import { LibRegistryItem } from "libraries/LibRegistryItem.sol";
import { LibRegistryModifier } from "libraries/LibRegistryModifier.sol";
import { LibRoom } from "libraries/LibRoom.sol";
import { LibStat } from "libraries/LibStat.sol";
import { LibTrade } from "libraries/LibTrade.sol";

// Components
import { AddressOperatorComponent, ID as AddressOperatorComponentID } from "components/AddressOperatorComponent.sol";
import { AffinityComponent, ID as AffinityComponentID } from "components/AffinityComponent.sol";
import { BalanceComponent, ID as BalanceComponentID } from "components/BalanceComponent.sol";
import { PowerComponent, ID as PowerComponentID } from "components/PowerComponent.sol";
import { BlockLastComponent, ID as BlockLastComponentID } from "components/BlockLastComponent.sol";
import { HarmonyComponent, ID as HarmonyComponentID } from "components/HarmonyComponent.sol";
import { HealthComponent, ID as HealthComponentID } from "components/HealthComponent.sol";
import { HealthCurrentComponent, ID as HealthCurrentComponentID } from "components/HealthCurrentComponent.sol";
import { CoinComponent, ID as CoinComponentID } from "components/CoinComponent.sol";
import { ExitsComponent, ID as ExitsComponentID } from "components/ExitsComponent.sol";
import { GenusComponent, ID as GenusComponentID } from "components/GenusComponent.sol";
import { IdAccountComponent, ID as IdAccountComponentID } from "components/IdAccountComponent.sol";
import { IdDelegateeComponent, ID as IdDelegateeComponentID } from "components/IdDelegateeComponent.sol";
import { IdDelegatorComponent, ID as IdDelegatorComponentID } from "components/IdDelegatorComponent.sol";
import { IdHolderComponent, ID as IdHolderComponentID } from "components/IdHolderComponent.sol";
import { IdMerchantComponent, ID as IdMerchantComponentID } from "components/IdMerchantComponent.sol";
import { IdNodeComponent, ID as IdNodeComponentID } from "components/IdNodeComponent.sol";
import { IdOwnerComponent, ID as IdOwnerComponentID } from "components/IdOwnerComponent.sol";
import { IdPetComponent, ID as IdPetComponentID } from "components/IdPetComponent.sol";
import { IdRequesteeComponent, ID as IdRequesteeComponentID } from "components/IdRequesteeComponent.sol";
import { IdRequesterComponent, ID as IdRequesterComponentID } from "components/IdRequesterComponent.sol";
import { IndexEquipComponent, ID as IndexEquipComponentID } from "components/IndexEquipComponent.sol";
import { IndexFoodComponent, ID as IndexFoodComponentID } from "components/IndexFoodComponent.sol";
import { IndexItemComponent, ID as IndexItemComponentID } from "components/IndexItemComponent.sol";
import { IndexModifierComponent, ID as IndexModifierComponentID } from "components/IndexModifierComponent.sol";
import { IndexPetComponent, ID as IndexPetComponentID } from "components/IndexPetComponent.sol";
import { IsAccountComponent, ID as IsAccountComponentID } from "components/IsAccountComponent.sol";
import { IsFoodComponent, ID as IsFoodComponentID } from "components/IsFoodComponent.sol";
import { IsFungibleComponent, ID as IsFungibleComponentID } from "components/IsFungibleComponent.sol";
import { IsInventoryComponent, ID as IsInventoryComponentID } from "components/IsInventoryComponent.sol";
import { IsListingComponent, ID as IsListingComponentID } from "components/IsListingComponent.sol";
import { IsMerchantComponent, ID as IsMerchantComponentID } from "components/IsMerchantComponent.sol";
import { IsModifierComponent, ID as IsModifierComponentID } from "components/IsModifierComponent.sol";
import { IsNodeComponent, ID as IsNodeComponentID } from "components/IsNodeComponent.sol";
import { IsNonFungibleComponent, ID as IsNonFungibleComponentID } from "components/IsNonFungibleComponent.sol";
import { IsPetComponent, ID as IsPetComponentID } from "components/IsPetComponent.sol";
import { IsProductionComponent, ID as IsProductionComponentID } from "components/IsProductionComponent.sol";
import { IsRegisterComponent, ID as IsRegisterComponentID } from "components/IsRegisterComponent.sol";
import { IsRegistryComponent, ID as IsRegistryComponentID } from "components/IsRegistryComponent.sol";
import { IsRegistryEntryComponent, ID as IsRegistryEntryComponentID } from "components/IsRegistryEntryComponent.sol";
import { IsRequestComponent, ID as IsRequestComponentID } from "components/IsRequestComponent.sol";
import { IsRoomComponent, ID as IsRoomComponentID } from "components/IsRoomComponent.sol";
import { IsTradeComponent, ID as IsTradeComponentID } from "components/IsTradeComponent.sol";
import { LocationComponent, ID as LocationComponentID } from "components/LocationComponent.sol";
import { MediaURIComponent, ID as MediaURIComponentID } from "components/MediaURIComponent.sol";
import { NameComponent, ID as NameComponentID } from "components/NameComponent.sol";
import { PriceBuyComponent, ID as PriceBuyComponentID } from "components/PriceBuyComponent.sol";
import { PriceSellComponent, ID as PriceSellComponentID } from "components/PriceSellComponent.sol";
import { PrototypeComponent, ID as PrototypeComponentID } from "components/PrototypeComponent.sol";
import { SlotsComponent, ID as SlotsComponentID } from "components/SlotsComponent.sol";
import { StateComponent, ID as StateComponentID } from "components/StateComponent.sol";
import { StatusComponent, ID as StatusComponentID } from "components/StatusComponent.sol";
import { TimeLastActionComponent, ID as TimeLastActionComponentID } from "components/TimeLastActionComponent.sol";
import { TimeStartComponent, ID as TimeStartComponentID } from "components/TimeStartComponent.sol";
import { TypeComponent, ID as TypeComponentID } from "components/TypeComponent.sol";
import { UpgradesComponent, ID as UpgradesComponentID } from "components/UpgradesComponent.sol";
import { ValueComponent, ID as ValueComponentID } from "components/ValueComponent.sol";
import { ViolenceComponent, ID as ViolenceComponentID } from "components/ViolenceComponent.sol";

// Systems
import { _InitSystem, ID as _InitSystemID } from "systems/_InitSystem.sol";
import { _devGiveTokensSystem, ID as _devGiveTokensSystemID } from "systems/_devGiveTokensSystem.sol";
import { _AddModifierSystem, ID as _AddModifierSystemID } from "systems/_AddModifierSystem.sol";
import { _ListingSetSystem, ID as _ListingSetSystemID } from "systems/_ListingSetSystem.sol";
import { _MerchantCreateSystem, ID as _MerchantCreateSystemID } from "systems/_MerchantCreateSystem.sol";
import { _NodeCreateSystem, ID as _NodeCreateSystemID } from "systems/_NodeCreateSystem.sol";
import { _RegistryCreateModSystem, ID as _RegistryCreateModSystemID } from "systems/_RegistryCreateModSystem.sol";
import { _RegistryUpdateModSystem, ID as _RegistryUpdateModSystemID } from "systems/_RegistryUpdateModSystem.sol";
import { _RegistryCreateEquipSystem, ID as _RegistryCreateEquipSystemID } from "systems/_RegistryCreateEquipSystem.sol";
import { _RegistryUpdateEquipSystem, ID as _RegistryUpdateEquipSystemID } from "systems/_RegistryUpdateEquipSystem.sol";
import { _RoomCreateSystem, ID as _RoomCreateSystemID } from "systems/_RoomCreateSystem.sol";
import { AccountMoveSystem, ID as AccountMoveSystemID } from "systems/AccountMoveSystem.sol";
import { AccountNameSystem, ID as AccountNameSystemID } from "systems/AccountNameSystem.sol";
import { AccountSetSystem, ID as AccountSetSystemID } from "systems/AccountSetSystem.sol";
import { ERC721PetSystem, ID as ERC721PetSystemID } from "systems/ERC721PetSystem.sol";
import { ListingBuySystem, ID as ListingBuySystemID } from "systems/ListingBuySystem.sol";
import { ListingSellSystem, ID as ListingSellSystemID } from "systems/ListingSellSystem.sol";
import { PetFoodSystem, ID as PetFoodSystemID } from "systems/PetFoodSystem.sol";
import { PetMetadataSystem, ID as PetMetadataSystemID } from "systems/PetMetadataSystem.sol";
import { PetNameSystem, ID as PetNameSystemID } from "systems/PetNameSystem.sol";
import { PetSetAccountSystem, ID as PetSetAccountSystemID } from "systems/PetSetAccountSystem.sol";
import { ProductionCollectSystem, ID as ProductionCollectSystemID } from "systems/ProductionCollectSystem.sol";
import { ProductionStartSystem, ID as ProductionStartSystemID } from "systems/ProductionStartSystem.sol";
import { ProductionStopSystem, ID as ProductionStopSystemID } from "systems/ProductionStopSystem.sol";
import { TradeAcceptSystem, ID as TradeAcceptSystemID } from "systems/TradeAcceptSystem.sol";
import { TradeAddToSystem, ID as TradeAddToSystemID } from "systems/TradeAddToSystem.sol";
import { TradeCancelSystem, ID as TradeCancelSystemID } from "systems/TradeCancelSystem.sol";
import { TradeConfirmSystem, ID as TradeConfirmSystemID } from "systems/TradeConfirmSystem.sol";
import { TradeInitiateSystem, ID as TradeInitiateSystemID } from "systems/TradeInitiateSystem.sol";

abstract contract TestSetupImports is MudTest {
// Components vars
AddressOperatorComponent _AddressOperatorComponent;
AffinityComponent _AffinityComponent;
BalanceComponent _BalanceComponent;
PowerComponent _PowerComponent;
BlockLastComponent _BlockLastComponent;
HarmonyComponent _HarmonyComponent;
HealthComponent _HealthComponent;
HealthCurrentComponent _HealthCurrentComponent;
CoinComponent _CoinComponent;
ExitsComponent _ExitsComponent;
GenusComponent _GenusComponent;
IdAccountComponent _IdAccountComponent;
IdDelegateeComponent _IdDelegateeComponent;
IdDelegatorComponent _IdDelegatorComponent;
IdHolderComponent _IdHolderComponent;
IdMerchantComponent _IdMerchantComponent;
IdNodeComponent _IdNodeComponent;
IdOwnerComponent _IdOwnerComponent;
IdPetComponent _IdPetComponent;
IdRequesteeComponent _IdRequesteeComponent;
IdRequesterComponent _IdRequesterComponent;
IndexEquipComponent _IndexEquipComponent;
IndexFoodComponent _IndexFoodComponent;
IndexItemComponent _IndexItemComponent;
IndexModifierComponent _IndexModifierComponent;
IndexPetComponent _IndexPetComponent;
IsAccountComponent _IsAccountComponent;
IsFoodComponent _IsFoodComponent;
IsFungibleComponent _IsFungibleComponent;
IsInventoryComponent _IsInventoryComponent;
IsListingComponent _IsListingComponent;
IsMerchantComponent _IsMerchantComponent;
IsModifierComponent _IsModifierComponent;
IsNodeComponent _IsNodeComponent;
IsNonFungibleComponent _IsNonFungibleComponent;
IsPetComponent _IsPetComponent;
IsProductionComponent _IsProductionComponent;
IsRegisterComponent _IsRegisterComponent;
IsRegistryComponent _IsRegistryComponent;
IsRegistryEntryComponent _IsRegistryEntryComponent;
IsRequestComponent _IsRequestComponent;
IsRoomComponent _IsRoomComponent;
IsTradeComponent _IsTradeComponent;
LocationComponent _LocationComponent;
MediaURIComponent _MediaURIComponent;
NameComponent _NameComponent;
PriceBuyComponent _PriceBuyComponent;
PriceSellComponent _PriceSellComponent;
PrototypeComponent _PrototypeComponent;
SlotsComponent _SlotsComponent;
StateComponent _StateComponent;
StatusComponent _StatusComponent;
TimeLastActionComponent _TimeLastActionComponent;
TimeStartComponent _TimeStartComponent;
TypeComponent _TypeComponent;
UpgradesComponent _UpgradesComponent;
ValueComponent _ValueComponent;
ViolenceComponent _ViolenceComponent;

// System vars
_InitSystem __InitSystem;
_devGiveTokensSystem __devGiveTokensSystem;
_AddModifierSystem __AddModifierSystem;
_ListingSetSystem __ListingSetSystem;
_MerchantCreateSystem __MerchantCreateSystem;
_NodeCreateSystem __NodeCreateSystem;
_RegistryCreateModSystem __RegistryCreateModSystem;
_RegistryUpdateModSystem __RegistryUpdateModSystem;
_RegistryCreateEquipSystem __RegistryCreateEquipSystem;
_RegistryUpdateEquipSystem __RegistryUpdateEquipSystem;
_RoomCreateSystem __RoomCreateSystem;
AccountMoveSystem _AccountMoveSystem;
AccountNameSystem _AccountNameSystem;
AccountSetSystem _AccountSetSystem;
ERC721PetSystem _ERC721PetSystem;
ListingBuySystem _ListingBuySystem;
ListingSellSystem _ListingSellSystem;
PetFoodSystem _PetFoodSystem;
PetMetadataSystem _PetMetadataSystem;
PetNameSystem _PetNameSystem;
PetSetAccountSystem _PetSetAccountSystem;
ProductionCollectSystem _ProductionCollectSystem;
ProductionStartSystem _ProductionStartSystem;
ProductionStopSystem _ProductionStopSystem;
TradeAcceptSystem _TradeAcceptSystem;
TradeAddToSystem _TradeAddToSystem;
TradeCancelSystem _TradeCancelSystem;
TradeConfirmSystem _TradeConfirmSystem;
TradeInitiateSystem _TradeInitiateSystem;

function setUp() public virtual override {
super.setUp();

_AddressOperatorComponent = AddressOperatorComponent(component(AddressOperatorComponentID));
_AffinityComponent = AffinityComponent(component(AffinityComponentID));
_BalanceComponent = BalanceComponent(component(BalanceComponentID));
_PowerComponent = PowerComponent(component(PowerComponentID));
_BlockLastComponent = BlockLastComponent(component(BlockLastComponentID));
_HarmonyComponent = HarmonyComponent(component(HarmonyComponentID));
_HealthComponent = HealthComponent(component(HealthComponentID));
_HealthCurrentComponent = HealthCurrentComponent(component(HealthCurrentComponentID));
_CoinComponent = CoinComponent(component(CoinComponentID));
_ExitsComponent = ExitsComponent(component(ExitsComponentID));
_GenusComponent = GenusComponent(component(GenusComponentID));
_IdAccountComponent = IdAccountComponent(component(IdAccountComponentID));
_IdDelegateeComponent = IdDelegateeComponent(component(IdDelegateeComponentID));
_IdDelegatorComponent = IdDelegatorComponent(component(IdDelegatorComponentID));
_IdHolderComponent = IdHolderComponent(component(IdHolderComponentID));
_IdMerchantComponent = IdMerchantComponent(component(IdMerchantComponentID));
_IdNodeComponent = IdNodeComponent(component(IdNodeComponentID));
_IdOwnerComponent = IdOwnerComponent(component(IdOwnerComponentID));
_IdPetComponent = IdPetComponent(component(IdPetComponentID));
_IdRequesteeComponent = IdRequesteeComponent(component(IdRequesteeComponentID));
_IdRequesterComponent = IdRequesterComponent(component(IdRequesterComponentID));
_IndexEquipComponent = IndexEquipComponent(component(IndexEquipComponentID));
_IndexFoodComponent = IndexFoodComponent(component(IndexFoodComponentID));
_IndexItemComponent = IndexItemComponent(component(IndexItemComponentID));
_IndexModifierComponent = IndexModifierComponent(component(IndexModifierComponentID));
_IndexPetComponent = IndexPetComponent(component(IndexPetComponentID));
_IsAccountComponent = IsAccountComponent(component(IsAccountComponentID));
_IsFoodComponent = IsFoodComponent(component(IsFoodComponentID));
_IsFungibleComponent = IsFungibleComponent(component(IsFungibleComponentID));
_IsInventoryComponent = IsInventoryComponent(component(IsInventoryComponentID));
_IsListingComponent = IsListingComponent(component(IsListingComponentID));
_IsMerchantComponent = IsMerchantComponent(component(IsMerchantComponentID));
_IsModifierComponent = IsModifierComponent(component(IsModifierComponentID));
_IsNodeComponent = IsNodeComponent(component(IsNodeComponentID));
_IsNonFungibleComponent = IsNonFungibleComponent(component(IsNonFungibleComponentID));
_IsPetComponent = IsPetComponent(component(IsPetComponentID));
_IsProductionComponent = IsProductionComponent(component(IsProductionComponentID));
_IsRegisterComponent = IsRegisterComponent(component(IsRegisterComponentID));
_IsRegistryComponent = IsRegistryComponent(component(IsRegistryComponentID));
_IsRegistryEntryComponent = IsRegistryEntryComponent(component(IsRegistryEntryComponentID));
_IsRequestComponent = IsRequestComponent(component(IsRequestComponentID));
_IsRoomComponent = IsRoomComponent(component(IsRoomComponentID));
_IsTradeComponent = IsTradeComponent(component(IsTradeComponentID));
_LocationComponent = LocationComponent(component(LocationComponentID));
_MediaURIComponent = MediaURIComponent(component(MediaURIComponentID));
_NameComponent = NameComponent(component(NameComponentID));
_PriceBuyComponent = PriceBuyComponent(component(PriceBuyComponentID));
_PriceSellComponent = PriceSellComponent(component(PriceSellComponentID));
_PrototypeComponent = PrototypeComponent(component(PrototypeComponentID));
_SlotsComponent = SlotsComponent(component(SlotsComponentID));
_StateComponent = StateComponent(component(StateComponentID));
_StatusComponent = StatusComponent(component(StatusComponentID));
_TimeLastActionComponent = TimeLastActionComponent(component(TimeLastActionComponentID));
_TimeStartComponent = TimeStartComponent(component(TimeStartComponentID));
_TypeComponent = TypeComponent(component(TypeComponentID));
_UpgradesComponent = UpgradesComponent(component(UpgradesComponentID));
_ValueComponent = ValueComponent(component(ValueComponentID));
_ViolenceComponent = ViolenceComponent(component(ViolenceComponentID));

__InitSystem = _InitSystem(system(_InitSystemID));
__devGiveTokensSystem = _devGiveTokensSystem(system(_devGiveTokensSystemID));
__AddModifierSystem = _AddModifierSystem(system(_AddModifierSystemID));
__ListingSetSystem = _ListingSetSystem(system(_ListingSetSystemID));
__MerchantCreateSystem = _MerchantCreateSystem(system(_MerchantCreateSystemID));
__NodeCreateSystem = _NodeCreateSystem(system(_NodeCreateSystemID));
__RegistryCreateModSystem = _RegistryCreateModSystem(system(_RegistryCreateModSystemID));
__RegistryUpdateModSystem = _RegistryUpdateModSystem(system(_RegistryUpdateModSystemID));
__RegistryCreateEquipSystem = _RegistryCreateEquipSystem(system(_RegistryCreateEquipSystemID));
__RegistryUpdateEquipSystem = _RegistryUpdateEquipSystem(system(_RegistryUpdateEquipSystemID));
__RoomCreateSystem = _RoomCreateSystem(system(_RoomCreateSystemID));
_AccountMoveSystem = AccountMoveSystem(system(AccountMoveSystemID));
_AccountNameSystem = AccountNameSystem(system(AccountNameSystemID));
_AccountSetSystem = AccountSetSystem(system(AccountSetSystemID));
_ERC721PetSystem = ERC721PetSystem(system(ERC721PetSystemID));
_ListingBuySystem = ListingBuySystem(system(ListingBuySystemID));
_ListingSellSystem = ListingSellSystem(system(ListingSellSystemID));
_PetFoodSystem = PetFoodSystem(system(PetFoodSystemID));
_PetMetadataSystem = PetMetadataSystem(system(PetMetadataSystemID));
_PetNameSystem = PetNameSystem(system(PetNameSystemID));
_PetSetAccountSystem = PetSetAccountSystem(system(PetSetAccountSystemID));
_ProductionCollectSystem = ProductionCollectSystem(system(ProductionCollectSystemID));
_ProductionStartSystem = ProductionStartSystem(system(ProductionStartSystemID));
_ProductionStopSystem = ProductionStopSystem(system(ProductionStopSystemID));
_TradeAcceptSystem = TradeAcceptSystem(system(TradeAcceptSystemID));
_TradeAddToSystem = TradeAddToSystem(system(TradeAddToSystemID));
_TradeCancelSystem = TradeCancelSystem(system(TradeCancelSystemID));
_TradeConfirmSystem = TradeConfirmSystem(system(TradeConfirmSystemID));
_TradeInitiateSystem = TradeInitiateSystem(system(TradeInitiateSystemID));
}
}