// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

////////////////////////
// AUTO GEN FILE 
// for components and systems import in one place

// Solecs
import { World } from "solecs/World.sol";
import { Component } from "solecs/Component.sol";
import { getAddressById } from "solecs/utils.sol";
import { IUint256Component } from "solecs/interfaces/IUint256Component.sol";
import { ISystem } from "solecs/interfaces/ISystem.sol";
import { IComponent } from "solecs/interfaces/IComponent.sol";

// Libraries
import { LibAccount } from "libraries/LibAccount.sol";
import { LibAffinity } from "libraries/LibAffinity.sol";
import { LibBonus } from "libraries/LibBonus.sol";
import { LibConfig } from "libraries/LibConfig.sol";
import { LibDataEntity } from "libraries/LibDataEntity.sol";
import { LibExperience } from "libraries/LibExperience.sol";
import { LibFlag } from "libraries/LibFlag.sol";
import { LibFriend } from "libraries/LibFriend.sol";
import { LibGacha } from "libraries/LibGacha.sol";
import { LibGoals } from "libraries/LibGoals.sol";
import { LibHarvest } from "libraries/LibHarvest.sol";
import { LibInventory } from "libraries/LibInventory.sol";
import { LibItemRegistry } from "libraries/LibItemRegistry.sol";
import { LibKill } from "libraries/LibKill.sol";
import { LibListing } from "libraries/LibListing.sol";
import { LibLootbox } from "libraries/LibLootbox.sol";
import { LibMint20 } from "libraries/LibMint20.sol";
import { LibNode } from "libraries/LibNode.sol";
import { LibNPC } from "libraries/LibNPC.sol";
import { LibPet721 } from "libraries/LibPet721.sol";
import { LibPet } from "libraries/LibPet.sol";
import { LibQuestRegistry } from "libraries/LibQuestRegistry.sol";
import { LibQuests } from "libraries/LibQuests.sol";
import { LibRarity } from "libraries/LibRarity.sol";
import { LibRelationshipRegistry } from "libraries/LibRelationshipRegistry.sol";
import { LibRelationship } from "libraries/LibRelationship.sol";
import { LibRoom } from "libraries/LibRoom.sol";
import { LibScore } from "libraries/LibScore.sol";
import { LibSkillRegistry } from "libraries/LibSkillRegistry.sol";
import { LibSkill } from "libraries/LibSkill.sol";
import { LibStat } from "libraries/LibStat.sol";
import { LibTimelock } from "libraries/LibTimelock.sol";
import { LibTraitRegistry } from "libraries/LibTraitRegistry.sol";
import { LibBoolean } from "libraries/utils/LibBoolean.sol";
import { LibHash } from "libraries/utils/LibHash.sol";
import { LibPack } from "libraries/utils/LibPack.sol";
import { LibRandom } from "libraries/utils/LibRandom.sol";


// Components
import { AddressOperatorComponent, ID as AddressOperatorComponentID } from "components/AddressOperatorComponent.sol";
import { AddressOwnerComponent, ID as AddressOwnerComponentID } from "components/AddressOwnerComponent.sol";
import { AffinityComponent, ID as AffinityComponentID } from "components/AffinityComponent.sol";
import { BlacklistComponent, ID as BlacklistComponentID } from "components/BlacklistComponent.sol";
import { BlockRevealComponent, ID as BlockRevealComponentID } from "components/BlockRevealComponent.sol";
import { CacheOperatorComponent, ID as CacheOperatorComponentID } from "components/CacheOperatorComponent.sol";
import { CostComponent, ID as CostComponentID } from "components/CostComponent.sol";
import { DescriptionAltComponent, ID as DescriptionAltComponentID } from "components/DescriptionAltComponent.sol";
import { DescriptionComponent, ID as DescriptionComponentID } from "components/DescriptionComponent.sol";
import { ExitsComponent, ID as ExitsComponentID } from "components/ExitsComponent.sol";
import { ExperienceComponent, ID as ExperienceComponentID } from "components/ExperienceComponent.sol";
import { FarcasterIndexComponent, ID as FarcasterIndexComponentID } from "components/FarcasterIndexComponent.sol";
import { ForComponent, ID as ForComponentID } from "components/ForComponent.sol";
import { HasFlagComponent, ID as HasFlagComponentID } from "components/HasFlagComponent.sol";
import { HashComponent, ID as HashComponentID } from "components/HashComponent.sol";
import { HarmonyComponent, ID as HarmonyComponentID } from "components/HarmonyComponent.sol";
import { HealthComponent, ID as HealthComponentID } from "components/HealthComponent.sol";
import { IdAccountComponent, ID as IdAccountComponentID } from "components/IdAccountComponent.sol";
import { IdDelegateeComponent, ID as IdDelegateeComponentID } from "components/IdDelegateeComponent.sol";
import { IdDelegatorComponent, ID as IdDelegatorComponentID } from "components/IdDelegatorComponent.sol";
import { IdHolderComponent, ID as IdHolderComponentID } from "components/IdHolderComponent.sol";
import { IDPointerComponent, ID as IDPointerComponentID } from "components/IDPointerComponent.sol";
import { IDOwnsInventoryComponent, ID as IDOwnsInventoryComponentID } from "components/IDOwnsInventoryComponent.sol";
import { IDOwnsQuestComponent, ID as IDOwnsQuestComponentID } from "components/IDOwnsQuestComponent.sol";
import { IDOwnsRelationshipComponent, ID as IDOwnsRelationshipComponentID } from "components/IDOwnsRelationshipComponent.sol";
import { IDOwnsPetComponent, ID as IDOwnsPetComponentID } from "components/IDOwnsPetComponent.sol";
import { IdNodeComponent, ID as IdNodeComponentID } from "components/IdNodeComponent.sol";
import { IdPetComponent, ID as IdPetComponentID } from "components/IdPetComponent.sol";
import { IDRoomComponent, ID as IDRoomComponentID } from "components/IDRoomComponent.sol";
import { IdSourceComponent, ID as IdSourceComponentID } from "components/IdSourceComponent.sol";
import { IDScoreTypeComponent, ID as IDScoreTypeComponentID } from "components/IDScoreTypeComponent.sol";
import { IdTargetComponent, ID as IdTargetComponentID } from "components/IdTargetComponent.sol";
import { IndexComponent, ID as IndexComponentID } from "components/IndexComponent.sol";
import { IndexAccountComponent, ID as IndexAccountComponentID } from "components/IndexAccountComponent.sol";
import { IndexBackgroundComponent, ID as IndexBackgroundComponentID } from "components/IndexBackgroundComponent.sol";
import { IndexBodyComponent, ID as IndexBodyComponentID } from "components/IndexBodyComponent.sol";
import { IndexColorComponent, ID as IndexColorComponentID } from "components/IndexColorComponent.sol";
import { IndexFaceComponent, ID as IndexFaceComponentID } from "components/IndexFaceComponent.sol";
import { IndexHandComponent, ID as IndexHandComponentID } from "components/IndexHandComponent.sol";
import { IndexItemComponent, ID as IndexItemComponentID } from "components/IndexItemComponent.sol";
import { IndexNodeComponent, ID as IndexNodeComponentID } from "components/IndexNodeComponent.sol";
import { IndexNPCComponent, ID as IndexNPCComponentID } from "components/IndexNPCComponent.sol";
import { IndexPetComponent, ID as IndexPetComponentID } from "components/IndexPetComponent.sol";
import { IndexQuestComponent, ID as IndexQuestComponentID } from "components/IndexQuestComponent.sol";
import { IndexRelationshipComponent, ID as IndexRelationshipComponentID } from "components/IndexRelationshipComponent.sol";
import { IndexRoomComponent, ID as IndexRoomComponentID } from "components/IndexRoomComponent.sol";
import { IndexSkillComponent, ID as IndexSkillComponentID } from "components/IndexSkillComponent.sol";
import { IsAccountComponent, ID as IsAccountComponentID } from "components/IsAccountComponent.sol";
import { IsBonusComponent, ID as IsBonusComponentID } from "components/IsBonusComponent.sol";
import { IsCompleteComponent, ID as IsCompleteComponentID } from "components/IsCompleteComponent.sol";
import { IsConsumableComponent, ID as IsConsumableComponentID } from "components/IsConsumableComponent.sol";
import { IsEffectComponent, ID as IsEffectComponentID } from "components/IsEffectComponent.sol";
import { IsEquippedComponent, ID as IsEquippedComponentID } from "components/IsEquippedComponent.sol";
import { IsFriendshipComponent, ID as IsFriendshipComponentID } from "components/IsFriendshipComponent.sol";
import { IsInventoryComponent, ID as IsInventoryComponentID } from "components/IsInventoryComponent.sol";
import { IsGoalComponent, ID as IsGoalComponentID } from "components/IsGoalComponent.sol";
import { IsKillComponent, ID as IsKillComponentID } from "components/IsKillComponent.sol";
import { IsListingComponent, ID as IsListingComponentID } from "components/IsListingComponent.sol";
import { IsLogComponent, ID as IsLogComponentID } from "components/IsLogComponent.sol";
import { IsLootboxComponent, ID as IsLootboxComponentID } from "components/IsLootboxComponent.sol";
import { IsNodeComponent, ID as IsNodeComponentID } from "components/IsNodeComponent.sol";
import { IsNPCComponent, ID as IsNPCComponentID } from "components/IsNPCComponent.sol";
import { IsPetComponent, ID as IsPetComponentID } from "components/IsPetComponent.sol";
import { IsProductionComponent, ID as IsProductionComponentID } from "components/IsProductionComponent.sol";
import { IsRegistryComponent, ID as IsRegistryComponentID } from "components/IsRegistryComponent.sol";
import { IsRelationshipComponent, ID as IsRelationshipComponentID } from "components/IsRelationshipComponent.sol";
import { IsRepeatableComponent, ID as IsRepeatableComponentID } from "components/IsRepeatableComponent.sol";
import { IsRequirementComponent, ID as IsRequirementComponentID } from "components/IsRequirementComponent.sol";
import { IsRewardComponent, ID as IsRewardComponentID } from "components/IsRewardComponent.sol";
import { IsRoomComponent, ID as IsRoomComponentID } from "components/IsRoomComponent.sol";
import { IsObjectiveComponent, ID as IsObjectiveComponentID } from "components/IsObjectiveComponent.sol";
import { IsQuestComponent, ID as IsQuestComponentID } from "components/IsQuestComponent.sol";
import { IsSkillComponent, ID as IsSkillComponentID } from "components/IsSkillComponent.sol";
import { KeysComponent, ID as KeysComponentID } from "components/KeysComponent.sol";
import { LevelComponent, ID as LevelComponentID } from "components/LevelComponent.sol";
import { LocationComponent, ID as LocationComponentID } from "components/LocationComponent.sol";
import { LogicTypeComponent, ID as LogicTypeComponentID } from "components/LogicTypeComponent.sol";
import { MaxComponent, ID as MaxComponentID } from "components/MaxComponent.sol";
import { MediaURIComponent, ID as MediaURIComponentID } from "components/MediaURIComponent.sol";
import { NameComponent, ID as NameComponentID } from "components/NameComponent.sol";
import { PowerComponent, ID as PowerComponentID } from "components/PowerComponent.sol";
import { PriceBuyComponent, ID as PriceBuyComponentID } from "components/PriceBuyComponent.sol";
import { PriceSellComponent, ID as PriceSellComponentID } from "components/PriceSellComponent.sol";
import { ProxyPermissionsFarm20Component, ID as ProxyPermissionsFarm20ComponentID } from "components/ProxyPermissionsFarm20Component.sol";
import { ProxyPermissionsERC721Component, ID as ProxyPermissionsERC721ComponentID } from "components/ProxyPermissionsERC721Component.sol";
import { ProxyPermissionsMint20Component, ID as ProxyPermissionsMint20ComponentID } from "components/ProxyPermissionsMint20Component.sol";
import { RarityComponent, ID as RarityComponentID } from "components/RarityComponent.sol";
import { RateComponent, ID as RateComponentID } from "components/RateComponent.sol";
import { RerollComponent, ID as RerollComponentID } from "components/RerollComponent.sol";
import { SkillPointComponent, ID as SkillPointComponentID } from "components/SkillPointComponent.sol";
import { SlotsComponent, ID as SlotsComponentID } from "components/SlotsComponent.sol";
import { StaminaComponent, ID as StaminaComponentID } from "components/StaminaComponent.sol";
import { StateComponent, ID as StateComponentID } from "components/StateComponent.sol";
import { SubtypeComponent, ID as SubtypeComponentID } from "components/SubtypeComponent.sol";
import { TimeComponent, ID as TimeComponentID } from "components/TimeComponent.sol";
import { TimeLastActionComponent, ID as TimeLastActionComponentID } from "components/TimeLastActionComponent.sol";
import { TimeLastComponent, ID as TimeLastComponentID } from "components/TimeLastComponent.sol";
import { TimelockComponent, ID as TimelockComponentID } from "components/TimelockComponent.sol";
import { TimeResetComponent, ID as TimeResetComponentID } from "components/TimeResetComponent.sol";
import { TimeStartComponent, ID as TimeStartComponentID } from "components/TimeStartComponent.sol";
import { TypeComponent, ID as TypeComponentID } from "components/TypeComponent.sol";
import { ValueComponent, ID as ValueComponentID } from "components/ValueComponent.sol";
import { ValuesComponent, ID as ValuesComponentID } from "components/ValuesComponent.sol";
import { ValueSignedComponent, ID as ValueSignedComponentID } from "components/ValueSignedComponent.sol";
import { ViolenceComponent, ID as ViolenceComponentID } from "components/ViolenceComponent.sol";
import { WeightsComponent, ID as WeightsComponentID } from "components/WeightsComponent.sol";
import { WhitelistComponent, ID as WhitelistComponentID } from "components/WhitelistComponent.sol";

// Systems
import { _ConfigSetSystem, ID as _ConfigSetSystemID } from "systems/_ConfigSetSystem.sol";
import { _GoalCreateSystem, ID as _GoalCreateSystemID } from "systems/_GoalCreateSystem.sol";
import { _GoalCreateRequirementSystem, ID as _GoalCreateRequirementSystemID } from "systems/_GoalCreateRequirementSystem.sol";
import { _GoalCreateRewardSystem, ID as _GoalCreateRewardSystemID } from "systems/_GoalCreateRewardSystem.sol";
import { _GoalDeleteSystem, ID as _GoalDeleteSystemID } from "systems/_GoalDeleteSystem.sol";
import { _ListingSetSystem, ID as _ListingSetSystemID } from "systems/_ListingSetSystem.sol";
import { _NodeCreateSystem, ID as _NodeCreateSystemID } from "systems/_NodeCreateSystem.sol";
import { _NodeDeleteSystem, ID as _NodeDeleteSystemID } from "systems/_NodeDeleteSystem.sol";
import { _NPCCreateSystem, ID as _NPCCreateSystemID } from "systems/_NPCCreateSystem.sol";
import { _NPCSetRoomSystem, ID as _NPCSetRoomSystemID } from "systems/_NPCSetRoomSystem.sol";
import { _NPCSetNameSystem, ID as _NPCSetNameSystemID } from "systems/_NPCSetNameSystem.sol";
import { _RegistryCreateItemConsumableSystem, ID as _RegistryCreateItemConsumableSystemID } from "systems/_RegistryCreateItemConsumableSystem.sol";
import { _RegistryCreateFoodSystem, ID as _RegistryCreateFoodSystemID } from "systems/_RegistryCreateFoodSystem.sol";
import { _RegistryCreateLootboxSystem, ID as _RegistryCreateLootboxSystemID } from "systems/_RegistryCreateLootboxSystem.sol";
import { _RegistryCreateQuestSystem, ID as _RegistryCreateQuestSystemID } from "systems/_RegistryCreateQuestSystem.sol";
import { _RegistryCreateQuestObjectiveSystem, ID as _RegistryCreateQuestObjectiveSystemID } from "systems/_RegistryCreateQuestObjectiveSystem.sol";
import { _RegistryCreateQuestRequirementSystem, ID as _RegistryCreateQuestRequirementSystemID } from "systems/_RegistryCreateQuestRequirementSystem.sol";
import { _RegistryCreateQuestRewardSystem, ID as _RegistryCreateQuestRewardSystemID } from "systems/_RegistryCreateQuestRewardSystem.sol";
import { _RegistryCreateRelationshipSystem, ID as _RegistryCreateRelationshipSystemID } from "systems/_RegistryCreateRelationshipSystem.sol";
import { _RegistryCreateReviveSystem, ID as _RegistryCreateReviveSystemID } from "systems/_RegistryCreateReviveSystem.sol";
import { _RegistryCreateSkillSystem, ID as _RegistryCreateSkillSystemID } from "systems/_RegistryCreateSkillSystem.sol";
import { _RegistryCreateSkillEffectSystem, ID as _RegistryCreateSkillEffectSystemID } from "systems/_RegistryCreateSkillEffectSystem.sol";
import { _RegistryCreateSkillRequirementSystem, ID as _RegistryCreateSkillRequirementSystemID } from "systems/_RegistryCreateSkillRequirementSystem.sol";
import { _RegistryCreateTraitSystem, ID as _RegistryCreateTraitSystemID } from "systems/_RegistryCreateTraitSystem.sol";
import { _RegistryDeleteTraitSystem, ID as _RegistryDeleteTraitSystemID } from "systems/_RegistryDeleteTraitSystem.sol";
import { _RegistryDeleteItemSystem, ID as _RegistryDeleteItemSystemID } from "systems/_RegistryDeleteItemSystem.sol";
import { _RegistryDeleteQuestSystem, ID as _RegistryDeleteQuestSystemID } from "systems/_RegistryDeleteQuestSystem.sol";
import { _RegistryDeleteSkillSystem, ID as _RegistryDeleteSkillSystemID } from "systems/_RegistryDeleteSkillSystem.sol";
import { _RegistryUpdateRelationshipSystem, ID as _RegistryUpdateRelationshipSystemID } from "systems/_RegistryUpdateRelationshipSystem.sol";
import { _RoomCreateGateSystem, ID as _RoomCreateGateSystemID } from "systems/_RoomCreateGateSystem.sol";
import { _RoomCreateSystem, ID as _RoomCreateSystemID } from "systems/_RoomCreateSystem.sol";
import { _RoomDeleteSystem, ID as _RoomDeleteSystemID } from "systems/_RoomDeleteSystem.sol";
import { AccountFundSystem, ID as AccountFundSystemID } from "systems/AccountFundSystem.sol";
import { AccountMoveSystem, ID as AccountMoveSystemID } from "systems/AccountMoveSystem.sol";
import { AccountRegisterSystem, ID as AccountRegisterSystemID } from "systems/AccountRegisterSystem.sol";
import { AccountSetNameSystem, ID as AccountSetNameSystemID } from "systems/AccountSetNameSystem.sol";
import { AccountSetOperatorSystem, ID as AccountSetOperatorSystemID } from "systems/AccountSetOperatorSystem.sol";
import { AccountSetFarcasterDataSystem, ID as AccountSetFarcasterDataSystemID } from "systems/AccountSetFarcasterDataSystem.sol";
import { Farm20ProxySystem, ID as Farm20ProxySystemID } from "systems/Farm20ProxySystem.sol";
import { Farm20DepositSystem, ID as Farm20DepositSystemID } from "systems/Farm20DepositSystem.sol";
import { Farm20WithdrawSystem, ID as Farm20WithdrawSystemID } from "systems/Farm20WithdrawSystem.sol";
import { FriendAcceptSystem, ID as FriendAcceptSystemID } from "systems/FriendAcceptSystem.sol";
import { FriendBlockSystem, ID as FriendBlockSystemID } from "systems/FriendBlockSystem.sol";
import { FriendCancelSystem, ID as FriendCancelSystemID } from "systems/FriendCancelSystem.sol";
import { FriendRequestSystem, ID as FriendRequestSystemID } from "systems/FriendRequestSystem.sol";
import { GoalContributeSystem, ID as GoalContributeSystemID } from "systems/GoalContributeSystem.sol";
import { GoalClaimSystem, ID as GoalClaimSystemID } from "systems/GoalClaimSystem.sol";
import { ListingBuySystem, ID as ListingBuySystemID } from "systems/ListingBuySystem.sol";
import { ListingSellSystem, ID as ListingSellSystemID } from "systems/ListingSellSystem.sol";
import { LootboxExecuteRevealSystem, ID as LootboxExecuteRevealSystemID } from "systems/LootboxExecuteRevealSystem.sol";
import { LootboxStartRevealSystem, ID as LootboxStartRevealSystemID } from "systems/LootboxStartRevealSystem.sol";
import { Mint20ProxySystem, ID as Mint20ProxySystemID } from "systems/Mint20ProxySystem.sol";
import { Pet721IsInWorldSystem, ID as Pet721IsInWorldSystemID } from "systems/Pet721IsInWorldSystem.sol";
import { Pet721MetadataSystem, ID as Pet721MetadataSystemID } from "systems/Pet721MetadataSystem.sol";
import { Pet721ProxySystem, ID as Pet721ProxySystemID } from "systems/Pet721ProxySystem.sol";
import { Pet721UnstakeSystem, ID as Pet721UnstakeSystemID } from "systems/Pet721UnstakeSystem.sol";
import { Pet721StakeSystem, ID as Pet721StakeSystemID } from "systems/Pet721StakeSystem.sol";
import { PetFeedSystem, ID as PetFeedSystemID } from "systems/PetFeedSystem.sol";
import { PetGachaMintSystem, ID as PetGachaMintSystemID } from "systems/PetGachaMintSystem.sol";
import { PetGachaRerollSystem, ID as PetGachaRerollSystemID } from "systems/PetGachaRerollSystem.sol";
import { PetGachaRevealSystem, ID as PetGachaRevealSystemID } from "systems/PetGachaRevealSystem.sol";
import { PetLevelSystem, ID as PetLevelSystemID } from "systems/PetLevelSystem.sol";
import { PetNameSystem, ID as PetNameSystemID } from "systems/PetNameSystem.sol";
import { PetReviveSystem, ID as PetReviveSystemID } from "systems/PetReviveSystem.sol";
import { PetUseItemSystem, ID as PetUseItemSystemID } from "systems/PetUseItemSystem.sol";
import { ProductionCollectSystem, ID as ProductionCollectSystemID } from "systems/ProductionCollectSystem.sol";
import { ProductionLiquidateSystem, ID as ProductionLiquidateSystemID } from "systems/ProductionLiquidateSystem.sol";
import { ProductionStartSystem, ID as ProductionStartSystemID } from "systems/ProductionStartSystem.sol";
import { ProductionStopSystem, ID as ProductionStopSystemID } from "systems/ProductionStopSystem.sol";
import { QuestAcceptSystem, ID as QuestAcceptSystemID } from "systems/QuestAcceptSystem.sol";
import { QuestCompleteSystem, ID as QuestCompleteSystemID } from "systems/QuestCompleteSystem.sol";
import { QuestDropSystem, ID as QuestDropSystemID } from "systems/QuestDropSystem.sol";
import { RelationshipAdvanceSystem, ID as RelationshipAdvanceSystemID } from "systems/RelationshipAdvanceSystem.sol";
import { SkillUpgradeSystem, ID as SkillUpgradeSystemID } from "systems/SkillUpgradeSystem.sol";
import { _721BatchMinterSystem, ID as _721BatchMinterSystemID } from "systems/_721BatchMinterSystem.sol";

