import { rm, writeFile } from 'fs/promises';
import { glob } from 'glob';
import path from 'path';
import { deferred } from '../../utils/deferred';
import { extractIdFromFile } from '../../utils/ids';
import { clientDir, componentsDir, deploymentDir, systemsDir } from '../../utils/paths';

export async function genClientSystemData(clear?: boolean) {
  const outputDir = clientDir + 'types/';
  if (clear) {
    console.log('Clearing system type output files', outputDir);
    await rm(path.join(outputDir, '/SystemTypes.ts'), { force: true });
    await rm(path.join(outputDir, '/SystemAbis.mjs'), { force: true });
    await rm(path.join(outputDir, '/SystemMappings.ts'), { force: true });
  }

  const { files: systems, ids } = await getMetadata(systemsDir);
  const abis = systems.map((system) => `../abi/${system}.json`);
  const types = systems.map((system) => `./ethers-contracts/${system}.ts`);

  const SystemMappings = genSystemMappings(systems, ids);
  const SystemTypes = genSystemTypes(systems, ids, types);
  const SystemAbis = genSystemAbis(systems, ids, abis);

  await writeFile(`${outputDir}/SystemTypes.ts`, SystemTypes);
  await writeFile(`${outputDir}/SystemAbis.mjs`, SystemAbis);
  await writeFile(`${outputDir}/SystemMappings.ts`, SystemMappings);
}

export async function genContractSystemData(clear?: boolean) {
  const outputDir = deploymentDir + 'contracts/mappings/';
  if (clear) {
    console.log('Clearing system type output files', outputDir);
    await rm(path.join(outputDir, '/SystemAbis.ts'), { force: true });
    await rm(path.join(outputDir, '/SystemMappings.ts'), { force: true });
  }

  const { files: systems, ids: sysIDs } = await getMetadata(systemsDir);
  const { files: comps, ids: compIDs } = await getMetadata(componentsDir);
  const bytecodes = systems.map((system) => `../../../out/${system}.sol/${system}.json`);

  const SystemBytecodes = genSystemBytecodes(systems, sysIDs, bytecodes);
  const SystemMappings = genSystemMappings(systems, sysIDs);
  const ComponentMappings = genCompMappings(comps, compIDs);

  await writeFile(`${outputDir}SystemBytecodes.ts`, SystemBytecodes);
  await writeFile(`${outputDir}SystemMappings.ts`, SystemMappings);
  await writeFile(`${outputDir}ComponentMappings.ts`, ComponentMappings);
}

/////////////
// INTERNAL

// gets files and ids for systems or components
async function getMetadata(dir: string) {
  const filesPath = `${dir}*.sol`;
  let files: string[] = [];
  let ids: string[] = [];

  const [resolve, , promise] = deferred<void>();
  glob(filesPath, {}, (_: any, matches: string[]) => {
    files = matches.map((path) => {
      const fragments = path.split('/');
      return fragments[fragments.length - 1].split('.sol')[0];
    });

    ids = matches.map((path, index) => {
      const id = extractIdFromFile(path);
      if (!id) {
        throw new Error(
          'No ID found for' +
            matches[index] +
            '. Make sure your system source file includes a ID definition (uint256 constant ID = uint256(keccak256(<ID>));)'
        );
      }
      return id;
    });

    resolve();
  });

  await promise; // Make the callback synchronous

  return { files, ids };
}

function genCompMappings(comps: string[], ids: string[]) {
  return `// Autogenerated 
  export const compToId = {
  ${comps.map((comp, index) => `  ${comp}: "${ids[index]}",`).join('\n')}
  };
  
  export const idToComp = {
  ${ids.map((id, index) => `  "${id}": "${comps[index]}",`).join('\n')}
  };
    `;
}

function genSystemMappings(systems: string[], ids: string[]) {
  return `// Autogenerated 
  export const systemToId = {
  ${systems.map((system, index) => `  ${system}: "${ids[index]}",`).join('\n')}
  };
  
  export const idToSystem = {
  ${ids.map((id, index) => `  "${id}": "${systems[index]}",`).join('\n')}
  };
    `;
}

function genSystemTypes(systems: string[], ids: string[], typePaths: string[]) {
  return `// Autogenerated
${typePaths
  .map((path, index) => `import { ${systems[index]} } from "${path.replace('.ts', '')}";`)
  .join('\n')}

export type SystemTypes = {
${systems.map((system, index) => `  "${ids[index]}": ${system};`).join('\n')}
};
`;
}

function genSystemAbis(systems: string[], ids: string[], abis: string[]) {
  return `// Autogenerated
${abis.map((path, index) => `import ${systems[index]} from "${path}";`).join('\n')}

export const SystemAbis = {
${systems.map((system, index) => `  "${ids[index]}": ${system}.abi,`).join('\n')}
};
`;
}

function genSystemBytecodes(systems: string[], ids: string[], abis: string[]) {
  return `// Autogenerated 
${abis.map((path, index) => `import ${systems[index]} from "${path}";`).join('\n')}

export const SystemBytecodes = {
${systems.map((system, index) => `  "${ids[index]}": ${system},`).join('\n')}
};
`;
}
