// Autogenerated using mud system-types
import _721BatchMinterSystem from "../../../../../client/abi/_721BatchMinterSystem.json";
import _AdminGiveSystem from "../../../../../client/abi/_AdminGiveSystem.json";
import _AuthManageRoleSystem from "../../../../../client/abi/_AuthManageRoleSystem.json";
import _ConfigSetSystem from "../../../../../client/abi/_ConfigSetSystem.json";
import _FactionRegistrySystem from "../../../../../client/abi/_FactionRegistrySystem.json";
import _GoalRegistrySystem from "../../../../../client/abi/_GoalRegistrySystem.json";
import _ItemRegistrySystem from "../../../../../client/abi/_ItemRegistrySystem.json";
import _ListingSetSystem from "../../../../../client/abi/_ListingSetSystem.json";
import _NodeRegistrySystem from "../../../../../client/abi/_NodeRegistrySystem.json";
import _NPCRegistrySystem from "../../../../../client/abi/_NPCRegistrySystem.json";
import _QuestRegistrySystem from "../../../../../client/abi/_QuestRegistrySystem.json";
import _RecipeRegistrySystem from "../../../../../client/abi/_RecipeRegistrySystem.json";
import _RelationshipRegistrySystem from "../../../../../client/abi/_RelationshipRegistrySystem.json";
import _RoomRegistrySystem from "../../../../../client/abi/_RoomRegistrySystem.json";
import _SkillRegistrySystem from "../../../../../client/abi/_SkillRegistrySystem.json";
import _TraitRegistrySystem from "../../../../../client/abi/_TraitRegistrySystem.json";
import AccountConsumeSystem from "../../../../../client/abi/AccountConsumeSystem.json";
import AccountFundSystem from "../../../../../client/abi/AccountFundSystem.json";
import AccountMoveSystem from "../../../../../client/abi/AccountMoveSystem.json";
import AccountRegisterSystem from "../../../../../client/abi/AccountRegisterSystem.json";
import AccountSetFarcasterDataSystem from "../../../../../client/abi/AccountSetFarcasterDataSystem.json";
import AccountSetNameSystem from "../../../../../client/abi/AccountSetNameSystem.json";
import AccountSetOperatorSystem from "../../../../../client/abi/AccountSetOperatorSystem.json";
import CraftSystem from "../../../../../client/abi/CraftSystem.json";
import DroptableRevealSystem from "../../../../../client/abi/DroptableRevealSystem.json";
import Farm20DepositSystem from "../../../../../client/abi/Farm20DepositSystem.json";
import Farm20ProxySystem from "../../../../../client/abi/Farm20ProxySystem.json";
import Farm20WithdrawSystem from "../../../../../client/abi/Farm20WithdrawSystem.json";
import FriendAcceptSystem from "../../../../../client/abi/FriendAcceptSystem.json";
import FriendBlockSystem from "../../../../../client/abi/FriendBlockSystem.json";
import FriendCancelSystem from "../../../../../client/abi/FriendCancelSystem.json";
import FriendRequestSystem from "../../../../../client/abi/FriendRequestSystem.json";
import GoalClaimSystem from "../../../../../client/abi/GoalClaimSystem.json";
import GoalContributeSystem from "../../../../../client/abi/GoalContributeSystem.json";
import ItemBurnSystem from "../../../../../client/abi/ItemBurnSystem.json";
import ListingBuySystem from "../../../../../client/abi/ListingBuySystem.json";
import ListingSellSystem from "../../../../../client/abi/ListingSellSystem.json";
import LootboxCommitSystem from "../../../../../client/abi/LootboxCommitSystem.json";
import Mint20ProxySystem from "../../../../../client/abi/Mint20ProxySystem.json";
import Pet721IsInWorldSystem from "../../../../../client/abi/Pet721IsInWorldSystem.json";
import Pet721MetadataSystem from "../../../../../client/abi/Pet721MetadataSystem.json";
import Pet721ProxySystem from "../../../../../client/abi/Pet721ProxySystem.json";
import Pet721StakeSystem from "../../../../../client/abi/Pet721StakeSystem.json";
import Pet721UnstakeSystem from "../../../../../client/abi/Pet721UnstakeSystem.json";
import PetFeedSystem from "../../../../../client/abi/PetFeedSystem.json";
import PetGachaMintSystem from "../../../../../client/abi/PetGachaMintSystem.json";
import PetGachaRerollSystem from "../../../../../client/abi/PetGachaRerollSystem.json";
import PetGachaRevealSystem from "../../../../../client/abi/PetGachaRevealSystem.json";
import PetLevelSystem from "../../../../../client/abi/PetLevelSystem.json";
import PetNameSystem from "../../../../../client/abi/PetNameSystem.json";
import PetReviveSystem from "../../../../../client/abi/PetReviveSystem.json";
import PetUseItemSystem from "../../../../../client/abi/PetUseItemSystem.json";
import ProductionCollectSystem from "../../../../../client/abi/ProductionCollectSystem.json";
import ProductionLiquidateSystem from "../../../../../client/abi/ProductionLiquidateSystem.json";
import ProductionStartSystem from "../../../../../client/abi/ProductionStartSystem.json";
import ProductionStopSystem from "../../../../../client/abi/ProductionStopSystem.json";
import QuestAcceptSystem from "../../../../../client/abi/QuestAcceptSystem.json";
import QuestCompleteSystem from "../../../../../client/abi/QuestCompleteSystem.json";
import QuestDropSystem from "../../../../../client/abi/QuestDropSystem.json";
import RelationshipAdvanceSystem from "../../../../../client/abi/RelationshipAdvanceSystem.json";
import ScavengeClaimSystem from "../../../../../client/abi/ScavengeClaimSystem.json";
import SkillUpgradeSystem from "../../../../../client/abi/SkillUpgradeSystem.json";
import TradeAcceptSystem from "../../../../../client/abi/TradeAcceptSystem.json";
import TradeAddToSystem from "../../../../../client/abi/TradeAddToSystem.json";
import TradeCancelSystem from "../../../../../client/abi/TradeCancelSystem.json";
import TradeConfirmSystem from "../../../../../client/abi/TradeConfirmSystem.json";
import TradeInitiateSystem from "../../../../../client/abi/TradeInitiateSystem.json";

export const SystemAbis = {
  "system.Pet721.BatchMint": _721BatchMinterSystem.abi,
  "system._Admin.Give": _AdminGiveSystem.abi,
  "system._Auth.Manage.Role": _AuthManageRoleSystem.abi,
  "system._Config.Set": _ConfigSetSystem.abi,
  "system.faction.registry": _FactionRegistrySystem.abi,
  "system.goal.registry": _GoalRegistrySystem.abi,
  "system.item.registry": _ItemRegistrySystem.abi,
  "system._Listing.Set": _ListingSetSystem.abi,
  "system.node.registry": _NodeRegistrySystem.abi,
  "system.npc.registry": _NPCRegistrySystem.abi,
  "system.quest.registry": _QuestRegistrySystem.abi,
  "system.recipe.registry": _RecipeRegistrySystem.abi,
  "system.relationship.registry": _RelationshipRegistrySystem.abi,
  "system.room.registry": _RoomRegistrySystem.abi,
  "system.skill.registry": _SkillRegistrySystem.abi,
  "system.trait.registry": _TraitRegistrySystem.abi,
  "system.Account.Consume": AccountConsumeSystem.abi,
  "system.Account.Fund": AccountFundSystem.abi,
  "system.Account.Move": AccountMoveSystem.abi,
  "system.Account.Register": AccountRegisterSystem.abi,
  "system.Account.Set.FarcasterData": AccountSetFarcasterDataSystem.abi,
  "system.Account.Set.Name": AccountSetNameSystem.abi,
  "system.Account.Set.Operator": AccountSetOperatorSystem.abi,
  "system.craft": CraftSystem.abi,
  "system.droptable.item.reveal": DroptableRevealSystem.abi,
  "system.Farm20.Deposit": Farm20DepositSystem.abi,
  "system.Farm20.Proxy": Farm20ProxySystem.abi,
  "system.Farm20.Withdraw": Farm20WithdrawSystem.abi,
  "system.Friend.Accept": FriendAcceptSystem.abi,
  "system.Friend.Block": FriendBlockSystem.abi,
  "system.Friend.Cancel": FriendCancelSystem.abi,
  "system.Friend.Request": FriendRequestSystem.abi,
  "system.Goal.Claim": GoalClaimSystem.abi,
  "system.Goal.Contribute": GoalContributeSystem.abi,
  "system.item.burn": ItemBurnSystem.abi,
  "system.Listing.Buy": ListingBuySystem.abi,
  "system.Listing.Sell": ListingSellSystem.abi,
  "system.Lootbox.Commit": LootboxCommitSystem.abi,
  "system.Mint20.Proxy": Mint20ProxySystem.abi,
  "system.Pet721.IsInWorld": Pet721IsInWorldSystem.abi,
  "system.Pet721.Metadata": Pet721MetadataSystem.abi,
  "system.Pet721.Proxy": Pet721ProxySystem.abi,
  "system.Pet721.Stake": Pet721StakeSystem.abi,
  "system.Pet721.Unstake": Pet721UnstakeSystem.abi,
  "system.Pet.Feed": PetFeedSystem.abi,
  "system.Pet.Gacha.Mint": PetGachaMintSystem.abi,
  "system.Pet.Gacha.Reroll": PetGachaRerollSystem.abi,
  "system.Pet.Gacha.Reveal": PetGachaRevealSystem.abi,
  "system.Pet.Level": PetLevelSystem.abi,
  "system.Pet.Name": PetNameSystem.abi,
  "system.Pet.Revive": PetReviveSystem.abi,
  "system.Pet.Use.Item": PetUseItemSystem.abi,
  "system.Production.Collect": ProductionCollectSystem.abi,
  "system.Production.Liquidate": ProductionLiquidateSystem.abi,
  "system.Production.Start": ProductionStartSystem.abi,
  "system.Production.Stop": ProductionStopSystem.abi,
  "system.Quest.Accept": QuestAcceptSystem.abi,
  "system.Quest.Complete": QuestCompleteSystem.abi,
  "system.Quest.Drop": QuestDropSystem.abi,
  "system.Relationship.Advance": RelationshipAdvanceSystem.abi,
  "system.Scavenge.Claim": ScavengeClaimSystem.abi,
  "system.Skill.Upgrade": SkillUpgradeSystem.abi,
  "system.Trade.Accept": TradeAcceptSystem.abi,
  "system.Trade.AddTo": TradeAddToSystem.abi,
  "system.Trade.Cancel": TradeCancelSystem.abi,
  "system.Trade.Confirm": TradeConfirmSystem.abi,
  "system.Trade.Initiate": TradeInitiateSystem.abi,
};
