// Autogenerated using mud system-types
import _721BatchMinterSystem from "../../../../../client/abi/_721BatchMinterSystem.json";
import _AuthManageRoleSystem from "../../../../../client/abi/_AuthManageRoleSystem.json";
import _ConfigSetSystem from "../../../../../client/abi/_ConfigSetSystem.json";
import _GoalCreateRequirementSystem from "../../../../../client/abi/_GoalCreateRequirementSystem.json";
import _GoalCreateRewardSystem from "../../../../../client/abi/_GoalCreateRewardSystem.json";
import _GoalCreateSystem from "../../../../../client/abi/_GoalCreateSystem.json";
import _GoalDeleteSystem from "../../../../../client/abi/_GoalDeleteSystem.json";
import _ListingSetSystem from "../../../../../client/abi/_ListingSetSystem.json";
import _NodeCreateSystem from "../../../../../client/abi/_NodeCreateSystem.json";
import _NodeDeleteSystem from "../../../../../client/abi/_NodeDeleteSystem.json";
import _NPCCreateSystem from "../../../../../client/abi/_NPCCreateSystem.json";
import _NPCSetNameSystem from "../../../../../client/abi/_NPCSetNameSystem.json";
import _NPCSetRoomSystem from "../../../../../client/abi/_NPCSetRoomSystem.json";
import _RegistryCreateFoodSystem from "../../../../../client/abi/_RegistryCreateFoodSystem.json";
import _RegistryCreateItemConsumableSystem from "../../../../../client/abi/_RegistryCreateItemConsumableSystem.json";
import _RegistryCreateLootboxSystem from "../../../../../client/abi/_RegistryCreateLootboxSystem.json";
import _RegistryCreateQuestObjectiveSystem from "../../../../../client/abi/_RegistryCreateQuestObjectiveSystem.json";
import _RegistryCreateQuestRequirementSystem from "../../../../../client/abi/_RegistryCreateQuestRequirementSystem.json";
import _RegistryCreateQuestRewardSystem from "../../../../../client/abi/_RegistryCreateQuestRewardSystem.json";
import _RegistryCreateQuestSystem from "../../../../../client/abi/_RegistryCreateQuestSystem.json";
import _RegistryCreateRelationshipSystem from "../../../../../client/abi/_RegistryCreateRelationshipSystem.json";
import _RegistryCreateReviveSystem from "../../../../../client/abi/_RegistryCreateReviveSystem.json";
import _RegistryCreateSkillEffectSystem from "../../../../../client/abi/_RegistryCreateSkillEffectSystem.json";
import _RegistryCreateSkillRequirementSystem from "../../../../../client/abi/_RegistryCreateSkillRequirementSystem.json";
import _RegistryCreateSkillSystem from "../../../../../client/abi/_RegistryCreateSkillSystem.json";
import _RegistryCreateTraitSystem from "../../../../../client/abi/_RegistryCreateTraitSystem.json";
import _RegistryDeleteItemSystem from "../../../../../client/abi/_RegistryDeleteItemSystem.json";
import _RegistryDeleteQuestSystem from "../../../../../client/abi/_RegistryDeleteQuestSystem.json";
import _RegistryDeleteRelationshipSystem from "../../../../../client/abi/_RegistryDeleteRelationshipSystem.json";
import _RegistryDeleteSkillSystem from "../../../../../client/abi/_RegistryDeleteSkillSystem.json";
import _RegistryDeleteTraitSystem from "../../../../../client/abi/_RegistryDeleteTraitSystem.json";
import _RegistryUpdateRelationshipSystem from "../../../../../client/abi/_RegistryUpdateRelationshipSystem.json";
import _RoomCreateGateSystem from "../../../../../client/abi/_RoomCreateGateSystem.json";
import _RoomCreateSystem from "../../../../../client/abi/_RoomCreateSystem.json";
import _RoomDeleteSystem from "../../../../../client/abi/_RoomDeleteSystem.json";
import AccountFundSystem from "../../../../../client/abi/AccountFundSystem.json";
import AccountMoveSystem from "../../../../../client/abi/AccountMoveSystem.json";
import AccountRegisterSystem from "../../../../../client/abi/AccountRegisterSystem.json";
import AccountSetFarcasterDataSystem from "../../../../../client/abi/AccountSetFarcasterDataSystem.json";
import AccountSetNameSystem from "../../../../../client/abi/AccountSetNameSystem.json";
import AccountSetOperatorSystem from "../../../../../client/abi/AccountSetOperatorSystem.json";
import Farm20DepositSystem from "../../../../../client/abi/Farm20DepositSystem.json";
import Farm20ProxySystem from "../../../../../client/abi/Farm20ProxySystem.json";
import Farm20WithdrawSystem from "../../../../../client/abi/Farm20WithdrawSystem.json";
import FriendAcceptSystem from "../../../../../client/abi/FriendAcceptSystem.json";
import FriendBlockSystem from "../../../../../client/abi/FriendBlockSystem.json";
import FriendCancelSystem from "../../../../../client/abi/FriendCancelSystem.json";
import FriendRequestSystem from "../../../../../client/abi/FriendRequestSystem.json";
import GoalClaimSystem from "../../../../../client/abi/GoalClaimSystem.json";
import GoalContributeSystem from "../../../../../client/abi/GoalContributeSystem.json";
import ListingBuySystem from "../../../../../client/abi/ListingBuySystem.json";
import ListingSellSystem from "../../../../../client/abi/ListingSellSystem.json";
import LootboxExecuteRevealSystem from "../../../../../client/abi/LootboxExecuteRevealSystem.json";
import LootboxStartRevealSystem from "../../../../../client/abi/LootboxStartRevealSystem.json";
import Mint20MintSystem from "../../../../../client/abi/Mint20MintSystem.json";
import Mint20ProxySystem from "../../../../../client/abi/Mint20ProxySystem.json";
import Pet721IsInWorldSystem from "../../../../../client/abi/Pet721IsInWorldSystem.json";
import Pet721MetadataSystem from "../../../../../client/abi/Pet721MetadataSystem.json";
import Pet721MintSystem from "../../../../../client/abi/Pet721MintSystem.json";
import Pet721ProxySystem from "../../../../../client/abi/Pet721ProxySystem.json";
import Pet721RevealSystem from "../../../../../client/abi/Pet721RevealSystem.json";
import Pet721StakeSystem from "../../../../../client/abi/Pet721StakeSystem.json";
import Pet721UnstakeSystem from "../../../../../client/abi/Pet721UnstakeSystem.json";
import PetFeedSystem from "../../../../../client/abi/PetFeedSystem.json";
import PetGachaMintSystem from "../../../../../client/abi/PetGachaMintSystem.json";
import PetGachaRerollSystem from "../../../../../client/abi/PetGachaRerollSystem.json";
import PetGachaRevealSystem from "../../../../../client/abi/PetGachaRevealSystem.json";
import PetLevelSystem from "../../../../../client/abi/PetLevelSystem.json";
import PetNameSystem from "../../../../../client/abi/PetNameSystem.json";
import PetReviveSystem from "../../../../../client/abi/PetReviveSystem.json";
import PetUseItemSystem from "../../../../../client/abi/PetUseItemSystem.json";
import ProductionCollectSystem from "../../../../../client/abi/ProductionCollectSystem.json";
import ProductionLiquidateSystem from "../../../../../client/abi/ProductionLiquidateSystem.json";
import ProductionStartSystem from "../../../../../client/abi/ProductionStartSystem.json";
import ProductionStopSystem from "../../../../../client/abi/ProductionStopSystem.json";
import QuestAcceptSystem from "../../../../../client/abi/QuestAcceptSystem.json";
import QuestCompleteSystem from "../../../../../client/abi/QuestCompleteSystem.json";
import QuestDropSystem from "../../../../../client/abi/QuestDropSystem.json";
import RelationshipAdvanceSystem from "../../../../../client/abi/RelationshipAdvanceSystem.json";
import SkillUpgradeSystem from "../../../../../client/abi/SkillUpgradeSystem.json";
import TradeAcceptSystem from "../../../../../client/abi/TradeAcceptSystem.json";
import TradeAddToSystem from "../../../../../client/abi/TradeAddToSystem.json";
import TradeCancelSystem from "../../../../../client/abi/TradeCancelSystem.json";
import TradeConfirmSystem from "../../../../../client/abi/TradeConfirmSystem.json";
import TradeInitiateSystem from "../../../../../client/abi/TradeInitiateSystem.json";

export const SystemAbis = {
  "system.Pet721.BatchMint": _721BatchMinterSystem.abi,
  "system._Auth.Manage.Role": _AuthManageRoleSystem.abi,
  "system._Config.Set": _ConfigSetSystem.abi,
  "system.Goal.Create.Requirement": _GoalCreateRequirementSystem.abi,
  "system.Goal.Create.Reward": _GoalCreateRewardSystem.abi,
  "system.Goal.Create": _GoalCreateSystem.abi,
  "system.Goal.Delete": _GoalDeleteSystem.abi,
  "system._Listing.Set": _ListingSetSystem.abi,
  "system._Node.Create": _NodeCreateSystem.abi,
  "system._Node.Delete": _NodeDeleteSystem.abi,
  "system._NPC.Create": _NPCCreateSystem.abi,
  "system._NPC.Set.Name": _NPCSetNameSystem.abi,
  "system._NPC.Set.Room": _NPCSetRoomSystem.abi,
  "system._Registry.Food.Create": _RegistryCreateFoodSystem.abi,
  "system._Registry.Create.Item.Consumable": _RegistryCreateItemConsumableSystem.abi,
  "system._Registry.Lootbox.Create": _RegistryCreateLootboxSystem.abi,
  "system._Registry.Quest.Create.Objective": _RegistryCreateQuestObjectiveSystem.abi,
  "system._Registry.Quest.Create.Requirement": _RegistryCreateQuestRequirementSystem.abi,
  "system._Registry.Quest.Create.Reward": _RegistryCreateQuestRewardSystem.abi,
  "system._Registry.Quest.Create": _RegistryCreateQuestSystem.abi,
  "system._Registry.Relationship.Create": _RegistryCreateRelationshipSystem.abi,
  "system._Registry.Revive.Create": _RegistryCreateReviveSystem.abi,
  "system._Registry.Skill.Create.Effect": _RegistryCreateSkillEffectSystem.abi,
  "system._Registry.Skill.Create.Requirement": _RegistryCreateSkillRequirementSystem.abi,
  "system._Registry.Skill.Create": _RegistryCreateSkillSystem.abi,
  "system._Registry.Trait.Create": _RegistryCreateTraitSystem.abi,
  "system._Registry.Item.Delete": _RegistryDeleteItemSystem.abi,
  "system._Registry.Quest.Delete": _RegistryDeleteQuestSystem.abi,
  "system._Registry.Relationship.Delete": _RegistryDeleteRelationshipSystem.abi,
  "system._Registry.Skill.Delete": _RegistryDeleteSkillSystem.abi,
  "system._Registry.Trait.Delete": _RegistryDeleteTraitSystem.abi,
  "system._Registry.Relationship.Update": _RegistryUpdateRelationshipSystem.abi,
  "system._Room.Create.Gate": _RoomCreateGateSystem.abi,
  "system._Room.Create": _RoomCreateSystem.abi,
  "system._Room.Delete": _RoomDeleteSystem.abi,
  "system.Account.Fund": AccountFundSystem.abi,
  "system.Account.Move": AccountMoveSystem.abi,
  "system.Account.Register": AccountRegisterSystem.abi,
  "system.Account.Set.FarcasterData": AccountSetFarcasterDataSystem.abi,
  "system.Account.Set.Name": AccountSetNameSystem.abi,
  "system.Account.Set.Operator": AccountSetOperatorSystem.abi,
  "system.Farm20.Deposit": Farm20DepositSystem.abi,
  "system.Farm20.Proxy": Farm20ProxySystem.abi,
  "system.Farm20.Withdraw": Farm20WithdrawSystem.abi,
  "system.Friend.Accept": FriendAcceptSystem.abi,
  "system.Friend.Block": FriendBlockSystem.abi,
  "system.Friend.Cancel": FriendCancelSystem.abi,
  "system.Friend.Request": FriendRequestSystem.abi,
  "system.Goal.Claim": GoalClaimSystem.abi,
  "system.Goal.Contribute": GoalContributeSystem.abi,
  "system.Listing.Buy": ListingBuySystem.abi,
  "system.Listing.Sell": ListingSellSystem.abi,
  "system.Lootbox.Reveal.Execute": LootboxExecuteRevealSystem.abi,
  "system.Lootbox.Reveal.Start": LootboxStartRevealSystem.abi,
  "system.Mint20.Mint": Mint20MintSystem.abi,
  "system.Mint20.Proxy": Mint20ProxySystem.abi,
  "system.Pet721.IsInWorld": Pet721IsInWorldSystem.abi,
  "system.Pet721.Metadata": Pet721MetadataSystem.abi,
  "system.Pet721.Mint": Pet721MintSystem.abi,
  "system.Pet721.Proxy": Pet721ProxySystem.abi,
  "system.Pet721.Reveal": Pet721RevealSystem.abi,
  "system.Pet721.Stake": Pet721StakeSystem.abi,
  "system.Pet721.Unstake": Pet721UnstakeSystem.abi,
  "system.Pet.Feed": PetFeedSystem.abi,
  "system.Pet.Gacha.Mint": PetGachaMintSystem.abi,
  "system.Pet.Gacha.Reroll": PetGachaRerollSystem.abi,
  "system.Pet.Gacha.Reveal": PetGachaRevealSystem.abi,
  "system.Pet.Level": PetLevelSystem.abi,
  "system.Pet.Name": PetNameSystem.abi,
  "system.Pet.Revive": PetReviveSystem.abi,
  "system.Pet.Use.Item": PetUseItemSystem.abi,
  "system.Production.Collect": ProductionCollectSystem.abi,
  "system.Production.Liquidate": ProductionLiquidateSystem.abi,
  "system.Production.Start": ProductionStartSystem.abi,
  "system.Production.Stop": ProductionStopSystem.abi,
  "system.Quest.Accept": QuestAcceptSystem.abi,
  "system.Quest.Complete": QuestCompleteSystem.abi,
  "system.Quest.Drop": QuestDropSystem.abi,
  "system.Relationship.Advance": RelationshipAdvanceSystem.abi,
  "system.Skill.Upgrade": SkillUpgradeSystem.abi,
  "system.Trade.Accept": TradeAcceptSystem.abi,
  "system.Trade.AddTo": TradeAddToSystem.abi,
  "system.Trade.Cancel": TradeCancelSystem.abi,
  "system.Trade.Confirm": TradeConfirmSystem.abi,
  "system.Trade.Initiate": TradeInitiateSystem.abi,
};
