const CDN_BASE_URL = import.meta.env.VITE_CDN_BASE_URL || 'https://cdn.prod.kamigotchi.io';

const ost = (filename: string) => `${CDN_BASE_URL}/sound/ost/${filename}.mp3`;

export const abandoned = ost('abandoned');
export const abandonedCamp = ost('abandonedCamp');
export const amusement = ost('amusement');
export const arrival = ost('arrival');
export const brokenTube = ost('brokenTube');
export const canyonBridge = ost('canyonBridge');
export const cave = ost('cave');
export const caveCrossroads = ost('caveCrossroads');
export const charcoalMural = ost('charcoalMural');
export const collapsedTunnel = ost('collapsedTunnel');
export const engravedDoor = ost('engravedDoor');
export const floodMural = ost('floodMural');
export const fungusGarden = ost('fungusGarden');
export const geometricCliffs = ost('geometricCliffs');
export const giantsPalm = ost('giantsPalm');
export const glitter = ost('glitter');
export const guardianSkull = ost('guardianSkull');
export const hatchToNowhere = ost('hatchToNowhere');
export const k1 = ost('k1');
export const k11 = ost('k11');
export const k13 = ost('k13');
export const k14 = ost('k14');
export const k2 = ost('k2');
export const k3 = ost('k3');
export const k4 = ost('k4');
export const k5 = ost('k5');
export const k8 = ost('k8');
export const k9 = ost('k9');
export const lotusPool = ost('lotusPool');
export const market = ost('market');
export const mina = ost('mina');
export const mystique = ost('mystique');
export const radiantCrystal = ost('radiantCrystal');
export const reinforcedTunnel = ost('reinforcedTunnel');
export const sacrarium = ost('sacrarium');
export const scenicView = ost('scenicView');
export const sextantRooms = ost('sextantRooms');
export const shabbyDeck = ost('shabbyDeck');
export const shop = ost('shop');
export const slipperyPit = ost('slipperyPit');
export const stillStream = ost('stillStream');
export const technoTemple = ost('technoTemple');
export const templeCave = ost('templeCave');
export const templeOfTheWheel = ost('templeOfTheWheel');
export const thrivingMushrooms = ost('thrivingMushrooms');
export const toadstoolPlatforms = ost('toadstoolPlatforms');

export { ost };
