export const HELP_TEXT = [
  'You can deposit and withdraw supported',
  'ERC20 tokens through the Token Portal.',
  '\n',
  'Once deposited, assets are converted into',
  'in-world items you can freely spend and use.',
  'Deposited assets are available instantly,',
  'but withdrawals generate a pending Receipt',
  'which can be claimed after a delay (1wk atm).',
  '\n',
  'Import and Export taxes apply (1% + 1)',
  'are non-refundable and subject to change.',
  '\n',
  'Thank you for your patronage ^^',
  '\n',
  '---',
  '\n',
  'In all seriousness, the withdrawal delay is',
  'a safety measure, and the plan is to use fees',
  'as an economic heuristic to lower the delay',
  'for honest players. This mechanism remains',
  'unsolved and is open to discussion in the',
  'community Discord.',
];
