// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: kamiden.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { type CallContext, type CallOptions } from 'nice-grpc-common';

export const protobufPackage = 'kamiden';

/** Base type */
export interface Message {
  RoomIndex: number;
  AccountId: string;
  Message: string;
  /** optional uint64 BlockNumber = 5; */
  Timestamp: number;
}

export interface RoomRequest {
  RoomIndex: number;
  Timestamp: number;
  Size?: number | undefined;
}

export interface Movement {
  RoomIndex: number;
  AccountId: string;
  Timestamp: number;
}

export interface HarvestEnd {
  RoomIndex: number;
  KamiId: string;
  Timestamp: number;
}

export interface Kill {
  RoomIndex: number;
  KillerId: string;
  VictimId: string;
  Spoils: string;
  Timestamp: number;
}

export interface Feed {
  Movements: Movement[];
  HarvestEnds: HarvestEnd[];
  Kills: Kill[];
}

export interface RoomResponse {
  Messages: Message[];
  Feeds: Feed[];
}

export interface StreamRequest {}

export interface StreamResponse {
  Messages: Message[];
  Feed: Feed | undefined;
}

export interface AuctionBuy {
  ItemIndex: number;
  AccountIndex: number;
  Amount: number;
  Price: number;
  Timestamp: number;
}

export interface AuctionBuysRequest {
  ItemIndex?: number | undefined;
}

export interface AuctionBuysResponse {
  AuctionBuys: AuctionBuy[];
}

function createBaseMessage(): Message {
  return { RoomIndex: 0, AccountId: '', Message: '', Timestamp: 0 };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.RoomIndex !== 0) {
      writer.uint32(8).uint32(message.RoomIndex);
    }
    if (message.AccountId !== '') {
      writer.uint32(18).string(message.AccountId);
    }
    if (message.Message !== '') {
      writer.uint32(26).string(message.Message);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(32).uint64(message.Timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.RoomIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.AccountId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.Message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Message>): Message {
    return Message.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Message>): Message {
    const message = createBaseMessage();
    message.RoomIndex = object.RoomIndex ?? 0;
    message.AccountId = object.AccountId ?? '';
    message.Message = object.Message ?? '';
    message.Timestamp = object.Timestamp ?? 0;
    return message;
  },
};

function createBaseRoomRequest(): RoomRequest {
  return { RoomIndex: 0, Timestamp: 0, Size: undefined };
}

export const RoomRequest: MessageFns<RoomRequest> = {
  encode(message: RoomRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.RoomIndex !== 0) {
      writer.uint32(8).uint32(message.RoomIndex);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(16).uint64(message.Timestamp);
    }
    if (message.Size !== undefined) {
      writer.uint32(24).uint32(message.Size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.RoomIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Size = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RoomRequest>): RoomRequest {
    return RoomRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomRequest>): RoomRequest {
    const message = createBaseRoomRequest();
    message.RoomIndex = object.RoomIndex ?? 0;
    message.Timestamp = object.Timestamp ?? 0;
    message.Size = object.Size ?? undefined;
    return message;
  },
};

function createBaseMovement(): Movement {
  return { RoomIndex: 0, AccountId: '', Timestamp: 0 };
}

export const Movement: MessageFns<Movement> = {
  encode(message: Movement, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.RoomIndex !== 0) {
      writer.uint32(8).uint32(message.RoomIndex);
    }
    if (message.AccountId !== '') {
      writer.uint32(18).string(message.AccountId);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(24).uint64(message.Timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Movement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMovement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.RoomIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.AccountId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Movement>): Movement {
    return Movement.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Movement>): Movement {
    const message = createBaseMovement();
    message.RoomIndex = object.RoomIndex ?? 0;
    message.AccountId = object.AccountId ?? '';
    message.Timestamp = object.Timestamp ?? 0;
    return message;
  },
};

function createBaseHarvestEnd(): HarvestEnd {
  return { RoomIndex: 0, KamiId: '', Timestamp: 0 };
}

export const HarvestEnd: MessageFns<HarvestEnd> = {
  encode(message: HarvestEnd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.RoomIndex !== 0) {
      writer.uint32(8).uint32(message.RoomIndex);
    }
    if (message.KamiId !== '') {
      writer.uint32(18).string(message.KamiId);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(24).uint64(message.Timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HarvestEnd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHarvestEnd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.RoomIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.KamiId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<HarvestEnd>): HarvestEnd {
    return HarvestEnd.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HarvestEnd>): HarvestEnd {
    const message = createBaseHarvestEnd();
    message.RoomIndex = object.RoomIndex ?? 0;
    message.KamiId = object.KamiId ?? '';
    message.Timestamp = object.Timestamp ?? 0;
    return message;
  },
};

function createBaseKill(): Kill {
  return { RoomIndex: 0, KillerId: '', VictimId: '', Spoils: '', Timestamp: 0 };
}

export const Kill: MessageFns<Kill> = {
  encode(message: Kill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.RoomIndex !== 0) {
      writer.uint32(8).uint32(message.RoomIndex);
    }
    if (message.KillerId !== '') {
      writer.uint32(18).string(message.KillerId);
    }
    if (message.VictimId !== '') {
      writer.uint32(26).string(message.VictimId);
    }
    if (message.Spoils !== '') {
      writer.uint32(34).string(message.Spoils);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(40).uint64(message.Timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Kill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.RoomIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.KillerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.VictimId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.Spoils = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Kill>): Kill {
    return Kill.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Kill>): Kill {
    const message = createBaseKill();
    message.RoomIndex = object.RoomIndex ?? 0;
    message.KillerId = object.KillerId ?? '';
    message.VictimId = object.VictimId ?? '';
    message.Spoils = object.Spoils ?? '';
    message.Timestamp = object.Timestamp ?? 0;
    return message;
  },
};

function createBaseFeed(): Feed {
  return { Movements: [], HarvestEnds: [], Kills: [] };
}

export const Feed: MessageFns<Feed> = {
  encode(message: Feed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.Movements) {
      Movement.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.HarvestEnds) {
      HarvestEnd.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.Kills) {
      Kill.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Feed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Movements.push(Movement.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.HarvestEnds.push(HarvestEnd.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.Kills.push(Kill.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Feed>): Feed {
    return Feed.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Feed>): Feed {
    const message = createBaseFeed();
    message.Movements = object.Movements?.map((e) => Movement.fromPartial(e)) || [];
    message.HarvestEnds = object.HarvestEnds?.map((e) => HarvestEnd.fromPartial(e)) || [];
    message.Kills = object.Kills?.map((e) => Kill.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRoomResponse(): RoomResponse {
  return { Messages: [], Feeds: [] };
}

export const RoomResponse: MessageFns<RoomResponse> = {
  encode(message: RoomResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.Messages) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.Feeds) {
      Feed.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Feeds.push(Feed.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RoomResponse>): RoomResponse {
    return RoomResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RoomResponse>): RoomResponse {
    const message = createBaseRoomResponse();
    message.Messages = object.Messages?.map((e) => Message.fromPartial(e)) || [];
    message.Feeds = object.Feeds?.map((e) => Feed.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStreamRequest(): StreamRequest {
  return {};
}

export const StreamRequest: MessageFns<StreamRequest> = {
  encode(_: StreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StreamRequest>): StreamRequest {
    return StreamRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<StreamRequest>): StreamRequest {
    const message = createBaseStreamRequest();
    return message;
  },
};

function createBaseStreamResponse(): StreamResponse {
  return { Messages: [], Feed: undefined };
}

export const StreamResponse: MessageFns<StreamResponse> = {
  encode(message: StreamResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.Messages) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.Feed !== undefined) {
      Feed.encode(message.Feed, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Feed = Feed.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StreamResponse>): StreamResponse {
    return StreamResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StreamResponse>): StreamResponse {
    const message = createBaseStreamResponse();
    message.Messages = object.Messages?.map((e) => Message.fromPartial(e)) || [];
    message.Feed =
      object.Feed !== undefined && object.Feed !== null ? Feed.fromPartial(object.Feed) : undefined;
    return message;
  },
};

function createBaseAuctionBuy(): AuctionBuy {
  return { ItemIndex: 0, AccountIndex: 0, Amount: 0, Price: 0, Timestamp: 0 };
}

export const AuctionBuy: MessageFns<AuctionBuy> = {
  encode(message: AuctionBuy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ItemIndex !== 0) {
      writer.uint32(8).uint32(message.ItemIndex);
    }
    if (message.AccountIndex !== 0) {
      writer.uint32(16).uint32(message.AccountIndex);
    }
    if (message.Amount !== 0) {
      writer.uint32(24).uint32(message.Amount);
    }
    if (message.Price !== 0) {
      writer.uint32(32).uint64(message.Price);
    }
    if (message.Timestamp !== 0) {
      writer.uint32(40).uint64(message.Timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuctionBuy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuctionBuy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ItemIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.AccountIndex = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Amount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.Price = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.Timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AuctionBuy>): AuctionBuy {
    return AuctionBuy.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuctionBuy>): AuctionBuy {
    const message = createBaseAuctionBuy();
    message.ItemIndex = object.ItemIndex ?? 0;
    message.AccountIndex = object.AccountIndex ?? 0;
    message.Amount = object.Amount ?? 0;
    message.Price = object.Price ?? 0;
    message.Timestamp = object.Timestamp ?? 0;
    return message;
  },
};

function createBaseAuctionBuysRequest(): AuctionBuysRequest {
  return { ItemIndex: undefined };
}

export const AuctionBuysRequest: MessageFns<AuctionBuysRequest> = {
  encode(message: AuctionBuysRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ItemIndex !== undefined) {
      writer.uint32(8).uint32(message.ItemIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuctionBuysRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuctionBuysRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ItemIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AuctionBuysRequest>): AuctionBuysRequest {
    return AuctionBuysRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuctionBuysRequest>): AuctionBuysRequest {
    const message = createBaseAuctionBuysRequest();
    message.ItemIndex = object.ItemIndex ?? undefined;
    return message;
  },
};

function createBaseAuctionBuysResponse(): AuctionBuysResponse {
  return { AuctionBuys: [] };
}

export const AuctionBuysResponse: MessageFns<AuctionBuysResponse> = {
  encode(message: AuctionBuysResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.AuctionBuys) {
      AuctionBuy.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuctionBuysResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuctionBuysResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.AuctionBuys.push(AuctionBuy.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AuctionBuysResponse>): AuctionBuysResponse {
    return AuctionBuysResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuctionBuysResponse>): AuctionBuysResponse {
    const message = createBaseAuctionBuysResponse();
    message.AuctionBuys = object.AuctionBuys?.map((e) => AuctionBuy.fromPartial(e)) || [];
    return message;
  },
};

/** Replies */
export type KamidenServiceDefinition = typeof KamidenServiceDefinition;
export const KamidenServiceDefinition = {
  name: 'KamidenService',
  fullName: 'kamiden.KamidenService',
  methods: {
    /** Requests the latest block number based on the latest ECS state. */
    getRoomMessages: {
      name: 'GetRoomMessages',
      requestType: RoomRequest,
      requestStream: false,
      responseType: RoomResponse,
      responseStream: false,
      options: {},
    },
    /** Stream */
    subscribeToStream: {
      name: 'SubscribeToStream',
      requestType: StreamRequest,
      requestStream: false,
      responseType: StreamResponse,
      responseStream: true,
      options: {},
    },
    getAuctionBuys: {
      name: 'GetAuctionBuys',
      requestType: AuctionBuysRequest,
      requestStream: false,
      responseType: AuctionBuysResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface KamidenServiceImplementation<CallContextExt = {}> {
  /** Requests the latest block number based on the latest ECS state. */
  getRoomMessages(
    request: RoomRequest,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<RoomResponse>>;
  /** Stream */
  subscribeToStream(
    request: StreamRequest,
    context: CallContext & CallContextExt
  ): ServerStreamingMethodResult<DeepPartial<StreamResponse>>;
  getAuctionBuys(
    request: AuctionBuysRequest,
    context: CallContext & CallContextExt
  ): Promise<DeepPartial<AuctionBuysResponse>>;
}

export interface KamidenServiceClient<CallOptionsExt = {}> {
  /** Requests the latest block number based on the latest ECS state. */
  getRoomMessages(
    request: DeepPartial<RoomRequest>,
    options?: CallOptions & CallOptionsExt
  ): Promise<RoomResponse>;
  /** Stream */
  subscribeToStream(
    request: DeepPartial<StreamRequest>,
    options?: CallOptions & CallOptionsExt
  ): AsyncIterable<StreamResponse>;
  getAuctionBuys(
    request: DeepPartial<AuctionBuysRequest>,
    options?: CallOptions & CallOptionsExt
  ): Promise<AuctionBuysResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

export type ServerStreamingMethodResult<Response> = {
  [Symbol.asyncIterator](): AsyncIterator<Response, void>;
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
