// Autogenerated using mud system-types
import _721BatchMinterSystem from "../abi/_721BatchMinterSystem.json";
import _AdminGiveSystem from "../abi/_AdminGiveSystem.json";
import _AuctionRegistrySystem from "../abi/_AuctionRegistrySystem.json";
import _AuthManageRoleSystem from "../abi/_AuthManageRoleSystem.json";
import _ConfigSetSystem from "../abi/_ConfigSetSystem.json";
import _CreatePetSystem from "../abi/_CreatePetSystem.json";
import _FactionRegistrySystem from "../abi/_FactionRegistrySystem.json";
import _GoalRegistrySystem from "../abi/_GoalRegistrySystem.json";
import _ItemRegistrySystem from "../abi/_ItemRegistrySystem.json";
import _ListingRegistrySystem from "../abi/_ListingRegistrySystem.json";
import _NodeRegistrySystem from "../abi/_NodeRegistrySystem.json";
import _NPCRegistrySystem from "../abi/_NPCRegistrySystem.json";
import _QuestRegistrySystem from "../abi/_QuestRegistrySystem.json";
import _RecipeRegistrySystem from "../abi/_RecipeRegistrySystem.json";
import _RelationshipRegistrySystem from "../abi/_RelationshipRegistrySystem.json";
import _RoomRegistrySystem from "../abi/_RoomRegistrySystem.json";
import _SkillRegistrySystem from "../abi/_SkillRegistrySystem.json";
import _TraitRegistrySystem from "../abi/_TraitRegistrySystem.json";
import AccountMoveSystem from "../abi/AccountMoveSystem.json";
import AccountRegisterSystem from "../abi/AccountRegisterSystem.json";
import AccountSetNameSystem from "../abi/AccountSetNameSystem.json";
import AccountSetOperatorSystem from "../abi/AccountSetOperatorSystem.json";
import AccountSetPFPSystem from "../abi/AccountSetPFPSystem.json";
import AccountUseItemSystem from "../abi/AccountUseItemSystem.json";
import AuctionBuySystem from "../abi/AuctionBuySystem.json";
import ChatSystem from "../abi/ChatSystem.json";
import CraftSystem from "../abi/CraftSystem.json";
import DroptableRevealSystem from "../abi/DroptableRevealSystem.json";
import EchoKamisSystem from "../abi/EchoKamisSystem.json";
import EchoRoomSystem from "../abi/EchoRoomSystem.json";
import FriendAcceptSystem from "../abi/FriendAcceptSystem.json";
import FriendBlockSystem from "../abi/FriendBlockSystem.json";
import FriendCancelSystem from "../abi/FriendCancelSystem.json";
import FriendRequestSystem from "../abi/FriendRequestSystem.json";
import GetterSystem from "../abi/GetterSystem.json";
import GoalClaimSystem from "../abi/GoalClaimSystem.json";
import GoalContributeSystem from "../abi/GoalContributeSystem.json";
import HarvestCollectSystem from "../abi/HarvestCollectSystem.json";
import HarvestLiquidateSystem from "../abi/HarvestLiquidateSystem.json";
import HarvestStartSystem from "../abi/HarvestStartSystem.json";
import HarvestStopSystem from "../abi/HarvestStopSystem.json";
import ItemBurnSystem from "../abi/ItemBurnSystem.json";
import Kami721IsInWorldSystem from "../abi/Kami721IsInWorldSystem.json";
import Kami721MetadataSystem from "../abi/Kami721MetadataSystem.json";
import Kami721StakeSystem from "../abi/Kami721StakeSystem.json";
import Kami721UnstakeSystem from "../abi/Kami721UnstakeSystem.json";
import KamiGachaMintSystem from "../abi/KamiGachaMintSystem.json";
import KamiGachaRerollSystem from "../abi/KamiGachaRerollSystem.json";
import KamiGachaRevealSystem from "../abi/KamiGachaRevealSystem.json";
import KamiLevelSystem from "../abi/KamiLevelSystem.json";
import KamiNameSystem from "../abi/KamiNameSystem.json";
import KamiUseItemSystem from "../abi/KamiUseItemSystem.json";
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import LootboxCommitSystem from "../abi/LootboxCommitSystem.json";
import QuestAcceptSystem from "../abi/QuestAcceptSystem.json";
import QuestCompleteSystem from "../abi/QuestCompleteSystem.json";
import QuestDropSystem from "../abi/QuestDropSystem.json";
import RelationshipAdvanceSystem from "../abi/RelationshipAdvanceSystem.json";
import ScavengeClaimSystem from "../abi/ScavengeClaimSystem.json";
import SkillResetSystem from "../abi/SkillResetSystem.json";
import SkillUpgradeSystem from "../abi/SkillUpgradeSystem.json";
import TradeCancelSystem from "../abi/TradeCancelSystem.json";
import TradeCreateSystem from "../abi/TradeCreateSystem.json";
import TradeExecuteSystem from "../abi/TradeExecuteSystem.json";
import TradeModifySystem from "../abi/TradeModifySystem.json";

export const SystemAbis = {
  "system.Kami721.BatchMint": _721BatchMinterSystem.abi,
  "system._Admin.Give": _AdminGiveSystem.abi,
  "system.auction.registry": _AuctionRegistrySystem.abi,
  "system._Auth.Manage.Role": _AuthManageRoleSystem.abi,
  "system._Config.Set": _ConfigSetSystem.abi,
  "system.Kami721.create": _CreatePetSystem.abi,
  "system.faction.registry": _FactionRegistrySystem.abi,
  "system.goal.registry": _GoalRegistrySystem.abi,
  "system.item.registry": _ItemRegistrySystem.abi,
  "system.listing.registry": _ListingRegistrySystem.abi,
  "system.node.registry": _NodeRegistrySystem.abi,
  "system.npc.registry": _NPCRegistrySystem.abi,
  "system.quest.registry": _QuestRegistrySystem.abi,
  "system.recipe.registry.2": _RecipeRegistrySystem.abi,
  "system.relationship.registry": _RelationshipRegistrySystem.abi,
  "system.room.registry": _RoomRegistrySystem.abi,
  "system.skill.registry": _SkillRegistrySystem.abi,
  "system.trait.registry": _TraitRegistrySystem.abi,
  "system.account.move": AccountMoveSystem.abi,
  "system.account.register": AccountRegisterSystem.abi,
  "system.account.set.name": AccountSetNameSystem.abi,
  "system.account.set.operator": AccountSetOperatorSystem.abi,
  "system.account.set.pfp": AccountSetPFPSystem.abi,
  "system.account.use.item": AccountUseItemSystem.abi,
  "system.auction.buy": AuctionBuySystem.abi,
  "system.chat": ChatSystem.abi,
  "system.craft": CraftSystem.abi,
  "system.droptable.item.reveal": DroptableRevealSystem.abi,
  "system.echo.kamis": EchoKamisSystem.abi,
  "system.echo.room": EchoRoomSystem.abi,
  "system.friend.accept": FriendAcceptSystem.abi,
  "system.friend.block": FriendBlockSystem.abi,
  "system.friend.cancel": FriendCancelSystem.abi,
  "system.friend.request": FriendRequestSystem.abi,
  "system.getter": GetterSystem.abi,
  "system.goal.claim": GoalClaimSystem.abi,
  "system.goal.contribute": GoalContributeSystem.abi,
  "system.harvest.collect": HarvestCollectSystem.abi,
  "system.harvest.liquidate": HarvestLiquidateSystem.abi,
  "system.harvest.start": HarvestStartSystem.abi,
  "system.harvest.stop": HarvestStopSystem.abi,
  "system.item.burn": ItemBurnSystem.abi,
  "system.Kami721.IsInWorld": Kami721IsInWorldSystem.abi,
  "system.Kami721.Metadata": Kami721MetadataSystem.abi,
  "system.kami721.stake": Kami721StakeSystem.abi,
  "system.kami721.unstake": Kami721UnstakeSystem.abi,
  "system.kami.gacha.mint": KamiGachaMintSystem.abi,
  "system.kami.gacha.reroll": KamiGachaRerollSystem.abi,
  "system.kami.gacha.reveal": KamiGachaRevealSystem.abi,
  "system.kami.level": KamiLevelSystem.abi,
  "system.kami.name": KamiNameSystem.abi,
  "system.kami.use.item": KamiUseItemSystem.abi,
  "system.listing.buy": ListingBuySystem.abi,
  "system.listing.sell": ListingSellSystem.abi,
  "system.lootbox.commit": LootboxCommitSystem.abi,
  "system.quest.accept": QuestAcceptSystem.abi,
  "system.quest.complete": QuestCompleteSystem.abi,
  "system.quest.drop": QuestDropSystem.abi,
  "system.relationship.advance": RelationshipAdvanceSystem.abi,
  "system.scavenge.claim": ScavengeClaimSystem.abi,
  "system.skill.reset": SkillResetSystem.abi,
  "system.skill.upgrade": SkillUpgradeSystem.abi,
  "system.trade.cancel": TradeCancelSystem.abi,
  "system.trade.create": TradeCreateSystem.abi,
  "system.trade.execute": TradeExecuteSystem.abi,
  "system.trade.modify": TradeModifySystem.abi,
};
