// Autogenerated using mud system-types
import _ConfigSetStringSystem from "../abi/_ConfigSetStringSystem.json";
import _ConfigSetSystem from "../abi/_ConfigSetSystem.json";
import _devGiveTokensSystem from "../abi/_devGiveTokensSystem.json";
import _ListingSetSystem from "../abi/_ListingSetSystem.json";
import _MerchantCreateSystem from "../abi/_MerchantCreateSystem.json";
import _MerchantSetLocationSystem from "../abi/_MerchantSetLocationSystem.json";
import _MerchantSetNameSystem from "../abi/_MerchantSetNameSystem.json";
import _NodeCreateSystem from "../abi/_NodeCreateSystem.json";
import _NodeSetAffinitySystem from "../abi/_NodeSetAffinitySystem.json";
import _NodeSetDescriptionSystem from "../abi/_NodeSetDescriptionSystem.json";
import _NodeSetLocationSystem from "../abi/_NodeSetLocationSystem.json";
import _NodeSetNameSystem from "../abi/_NodeSetNameSystem.json";
import _RegistryCreateFoodSystem from "../abi/_RegistryCreateFoodSystem.json";
import _RegistryCreateGearSystem from "../abi/_RegistryCreateGearSystem.json";
import _RegistryCreateModSystem from "../abi/_RegistryCreateModSystem.json";
import _RegistryCreateQuestObjectiveSystem from "../abi/_RegistryCreateQuestObjectiveSystem.json";
import _RegistryCreateQuestRequirementSystem from "../abi/_RegistryCreateQuestRequirementSystem.json";
import _RegistryCreateQuestRewardSystem from "../abi/_RegistryCreateQuestRewardSystem.json";
import _RegistryCreateQuestSystem from "../abi/_RegistryCreateQuestSystem.json";
import _RegistryCreateReviveSystem from "../abi/_RegistryCreateReviveSystem.json";
import _RegistryCreateTraitSystem from "../abi/_RegistryCreateTraitSystem.json";
import _RegistryDeleteQuestSystem from "../abi/_RegistryDeleteQuestSystem.json";
import _RegistryUpdateFoodSystem from "../abi/_RegistryUpdateFoodSystem.json";
import _RegistryUpdateGearSystem from "../abi/_RegistryUpdateGearSystem.json";
import _RegistryUpdateModSystem from "../abi/_RegistryUpdateModSystem.json";
import _RegistryUpdateReviveSystem from "../abi/_RegistryUpdateReviveSystem.json";
import _RegistryUpdateTraitSystem from "../abi/_RegistryUpdateTraitSystem.json";
import _RoomCreateSystem from "../abi/_RoomCreateSystem.json";
import _RoomSetDescriptionSystem from "../abi/_RoomSetDescriptionSystem.json";
import _RoomSetExitsSystem from "../abi/_RoomSetExitsSystem.json";
import _RoomSetNameSystem from "../abi/_RoomSetNameSystem.json";
import AccountFundSystem from "../abi/AccountFundSystem.json";
import AccountMoveSystem from "../abi/AccountMoveSystem.json";
import AccountRegisterSystem from "../abi/AccountRegisterSystem.json";
import AccountSetNameSystem from "../abi/AccountSetNameSystem.json";
import AccountSetOperatorSystem from "../abi/AccountSetOperatorSystem.json";
import Farm20DepositSystem from "../abi/Farm20DepositSystem.json";
import Farm20ProxySystem from "../abi/Farm20ProxySystem.json";
import Farm20WithdrawSystem from "../abi/Farm20WithdrawSystem.json";
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import Mint20MintSystem from "../abi/Mint20MintSystem.json";
import Mint20ProxySystem from "../abi/Mint20ProxySystem.json";
import NodeCollectSystem from "../abi/NodeCollectSystem.json";
import Pet721MetadataSystem from "../abi/Pet721MetadataSystem.json";
import Pet721MintSystem from "../abi/Pet721MintSystem.json";
import Pet721ProxySystem from "../abi/Pet721ProxySystem.json";
import Pet721RevealSystem from "../abi/Pet721RevealSystem.json";
import Pet721StakeSystem from "../abi/Pet721StakeSystem.json";
import Pet721TransferSystem from "../abi/Pet721TransferSystem.json";
import Pet721UnstakeSystem from "../abi/Pet721UnstakeSystem.json";
import PetFeedSystem from "../abi/PetFeedSystem.json";
import PetLevelSystem from "../abi/PetLevelSystem.json";
import PetNameSystem from "../abi/PetNameSystem.json";
import PetReviveSystem from "../abi/PetReviveSystem.json";
import PetSetAccountSystem from "../abi/PetSetAccountSystem.json";
import ProductionCollectSystem from "../abi/ProductionCollectSystem.json";
import ProductionLiquidateSystem from "../abi/ProductionLiquidateSystem.json";
import ProductionStartSystem from "../abi/ProductionStartSystem.json";
import ProductionStopSystem from "../abi/ProductionStopSystem.json";
import QuestAcceptSystem from "../abi/QuestAcceptSystem.json";
import QuestCompleteSystem from "../abi/QuestCompleteSystem.json";
import TradeAcceptSystem from "../abi/TradeAcceptSystem.json";
import TradeAddToSystem from "../abi/TradeAddToSystem.json";
import TradeCancelSystem from "../abi/TradeCancelSystem.json";
import TradeConfirmSystem from "../abi/TradeConfirmSystem.json";
import TradeInitiateSystem from "../abi/TradeInitiateSystem.json";

export const SystemAbis = {
  "system._Config.Set.String": _ConfigSetStringSystem.abi,
  "system._Config.Set": _ConfigSetSystem.abi,
  "system._devGiveTokens": _devGiveTokensSystem.abi,
  "system._Listing.Set": _ListingSetSystem.abi,
  "system._Merchant.Create": _MerchantCreateSystem.abi,
  "system._Merchant.Set.Location": _MerchantSetLocationSystem.abi,
  "system._Merchant.Set.Name": _MerchantSetNameSystem.abi,
  "system._Node.Create": _NodeCreateSystem.abi,
  "system._Node.Set.Affinity": _NodeSetAffinitySystem.abi,
  "system._Node.Set.Description": _NodeSetDescriptionSystem.abi,
  "system._Node.Set.Location": _NodeSetLocationSystem.abi,
  "system._Node.Set.Name": _NodeSetNameSystem.abi,
  "system._Registry.Food.Create": _RegistryCreateFoodSystem.abi,
  "system._Registry.Gear.Create": _RegistryCreateGearSystem.abi,
  "system._Registry.Mod.Create": _RegistryCreateModSystem.abi,
  "system._Registry.Quest.Create.Objective": _RegistryCreateQuestObjectiveSystem.abi,
  "system._Registry.Quest.Create.Requirement": _RegistryCreateQuestRequirementSystem.abi,
  "system._Registry.Quest.Create.Reward": _RegistryCreateQuestRewardSystem.abi,
  "system._Registry.Quest.Create": _RegistryCreateQuestSystem.abi,
  "system._Registry.Revive.Create": _RegistryCreateReviveSystem.abi,
  "system._Registry.Trait.Create": _RegistryCreateTraitSystem.abi,
  "system._Registry.Quest.Delete": _RegistryDeleteQuestSystem.abi,
  "system._Registry.Food.Update": _RegistryUpdateFoodSystem.abi,
  "system._Registry.Gear.Update": _RegistryUpdateGearSystem.abi,
  "system._Registry.Mod.Update": _RegistryUpdateModSystem.abi,
  "system._Registry.Revive.Update": _RegistryUpdateReviveSystem.abi,
  "system._Registry.Trait.Update": _RegistryUpdateTraitSystem.abi,
  "system._Room.Create": _RoomCreateSystem.abi,
  "system._Room.Set.Description": _RoomSetDescriptionSystem.abi,
  "system._Room.Set.Exits": _RoomSetExitsSystem.abi,
  "system._Room.Set.Name": _RoomSetNameSystem.abi,
  "system.Account.Fund": AccountFundSystem.abi,
  "system.Account.Move": AccountMoveSystem.abi,
  "system.Account.Register": AccountRegisterSystem.abi,
  "system.Account.Set.Name": AccountSetNameSystem.abi,
  "system.Account.Set.Operator": AccountSetOperatorSystem.abi,
  "system.Farm20.Deposit": Farm20DepositSystem.abi,
  "system.Farm20.Proxy": Farm20ProxySystem.abi,
  "system.Farm20.Withdraw": Farm20WithdrawSystem.abi,
  "system.Listing.Buy": ListingBuySystem.abi,
  "system.Listing.Sell": ListingSellSystem.abi,
  "system.Mint20.Mint": Mint20MintSystem.abi,
  "system.Mint20.Proxy": Mint20ProxySystem.abi,
  "system.Node.Collect": NodeCollectSystem.abi,
  "system.Pet721.Metadata": Pet721MetadataSystem.abi,
  "system.Pet721.Mint": Pet721MintSystem.abi,
  "system.Pet721.Proxy": Pet721ProxySystem.abi,
  "system.Pet721.Reveal": Pet721RevealSystem.abi,
  "system.Pet721.Stake": Pet721StakeSystem.abi,
  "system.Pet721.Transfer": Pet721TransferSystem.abi,
  "system.Pet721.Unstake": Pet721UnstakeSystem.abi,
  "system.Pet.Feed": PetFeedSystem.abi,
  "system.Pet.Level": PetLevelSystem.abi,
  "system.Pet.Name": PetNameSystem.abi,
  "system.Pet.Revive": PetReviveSystem.abi,
  "system.Pet.SetAccount": PetSetAccountSystem.abi,
  "system.Production.Collect": ProductionCollectSystem.abi,
  "system.Production.Liquidate": ProductionLiquidateSystem.abi,
  "system.Production.Start": ProductionStartSystem.abi,
  "system.Production.Stop": ProductionStopSystem.abi,
  "system.Quest.Accept": QuestAcceptSystem.abi,
  "system.Quest.Complete": QuestCompleteSystem.abi,
  "system.Trade.Accept": TradeAcceptSystem.abi,
  "system.Trade.AddTo": TradeAddToSystem.abi,
  "system.Trade.Cancel": TradeCancelSystem.abi,
  "system.Trade.Confirm": TradeConfirmSystem.abi,
  "system.Trade.Initiate": TradeInitiateSystem.abi,
};
