// Autogenerated using mud system-types
import _ConfigSetStringSystem from "../abi/_ConfigSetStringSystem.json";
import _ConfigSetSystem from "../abi/_ConfigSetSystem.json";
import _devGiveTokensSystem from "../abi/_devGiveTokensSystem.json";
import _InitSystem from "../abi/_InitSystem.json";
import _ListingSetSystem from "../abi/_ListingSetSystem.json";
import _MerchantCreateSystem from "../abi/_MerchantCreateSystem.json";
import _NodeCreateSystem from "../abi/_NodeCreateSystem.json";
import _NodeSetAffinitySystem from "../abi/_NodeSetAffinitySystem.json";
import _NodeSetDescriptionSystem from "../abi/_NodeSetDescriptionSystem.json";
import _NodeSetLocationSystem from "../abi/_NodeSetLocationSystem.json";
import _NodeSetNameSystem from "../abi/_NodeSetNameSystem.json";
import _RegistryCreateFoodSystem from "../abi/_RegistryCreateFoodSystem.json";
import _RegistryCreateGearSystem from "../abi/_RegistryCreateGearSystem.json";
import _RegistryCreateModSystem from "../abi/_RegistryCreateModSystem.json";
import _RegistryCreateReviveSystem from "../abi/_RegistryCreateReviveSystem.json";
import _RegistryCreateTraitSystem from "../abi/_RegistryCreateTraitSystem.json";
import _RegistryUpdateFoodSystem from "../abi/_RegistryUpdateFoodSystem.json";
import _RegistryUpdateGearSystem from "../abi/_RegistryUpdateGearSystem.json";
import _RegistryUpdateModSystem from "../abi/_RegistryUpdateModSystem.json";
import _RegistryUpdateReviveSystem from "../abi/_RegistryUpdateReviveSystem.json";
import _RegistryUpdateTraitSystem from "../abi/_RegistryUpdateTraitSystem.json";
import _RoomCreateSystem from "../abi/_RoomCreateSystem.json";
import _SetLeaderboardEpochSystem from "../abi/_SetLeaderboardEpochSystem.json";
import AccountMoveSystem from "../abi/AccountMoveSystem.json";
import AccountRegisterSystem from "../abi/AccountRegisterSystem.json";
import AccountSetNameSystem from "../abi/AccountSetNameSystem.json";
import AccountSetOperatorSystem from "../abi/AccountSetOperatorSystem.json";
import ERC20DepositSystem from "../abi/ERC20DepositSystem.json";
import ERC20ProxySystem from "../abi/ERC20ProxySystem.json";
import ERC20WithdrawSystem from "../abi/ERC20WithdrawSystem.json";
import ERC721MetadataSystem from "../abi/ERC721MetadataSystem.json";
import ERC721MintSystem from "../abi/ERC721MintSystem.json";
import ERC721ProxySystem from "../abi/ERC721ProxySystem.json";
import ERC721StakeSystem from "../abi/ERC721StakeSystem.json";
import ERC721TransferSystem from "../abi/ERC721TransferSystem.json";
import ERC721UnstakeSystem from "../abi/ERC721UnstakeSystem.json";
import ListingBuySystem from "../abi/ListingBuySystem.json";
import ListingSellSystem from "../abi/ListingSellSystem.json";
import NodeCollectSystem from "../abi/NodeCollectSystem.json";
import PetFeedSystem from "../abi/PetFeedSystem.json";
import PetNameSystem from "../abi/PetNameSystem.json";
import PetReviveSystem from "../abi/PetReviveSystem.json";
import PetSetAccountSystem from "../abi/PetSetAccountSystem.json";
import ProductionCollectSystem from "../abi/ProductionCollectSystem.json";
import ProductionLiquidateSystem from "../abi/ProductionLiquidateSystem.json";
import ProductionStartSystem from "../abi/ProductionStartSystem.json";
import ProductionStopSystem from "../abi/ProductionStopSystem.json";
import TradeAcceptSystem from "../abi/TradeAcceptSystem.json";
import TradeAddToSystem from "../abi/TradeAddToSystem.json";
import TradeCancelSystem from "../abi/TradeCancelSystem.json";
import TradeConfirmSystem from "../abi/TradeConfirmSystem.json";
import TradeInitiateSystem from "../abi/TradeInitiateSystem.json";

export const SystemAbis = {
  "system._Config.Set.String": _ConfigSetStringSystem.abi,
  "system._Config.Set": _ConfigSetSystem.abi,
  "system._devGiveTokens": _devGiveTokensSystem.abi,
  "system._Init": _InitSystem.abi,
  "system._Listing.Set": _ListingSetSystem.abi,
  "system._Merchant.Create": _MerchantCreateSystem.abi,
  "system._Node.Create": _NodeCreateSystem.abi,
  "system._Node.Set.Affinity": _NodeSetAffinitySystem.abi,
  "system._Node.Set.Description": _NodeSetDescriptionSystem.abi,
  "system._Node.Set.Location": _NodeSetLocationSystem.abi,
  "system._Node.Set.Name": _NodeSetNameSystem.abi,
  "system._Registry.Food.Create": _RegistryCreateFoodSystem.abi,
  "system._Registry.Gear.Create": _RegistryCreateGearSystem.abi,
  "system._Registry.Mod.Create": _RegistryCreateModSystem.abi,
  "system._Registry.Revive.Create": _RegistryCreateReviveSystem.abi,
  "system._Registry.Trait.Create": _RegistryCreateTraitSystem.abi,
  "system._Registry.Food.Update": _RegistryUpdateFoodSystem.abi,
  "system._Registry.Gear.Update": _RegistryUpdateGearSystem.abi,
  "system._Registry.Mod.Update": _RegistryUpdateModSystem.abi,
  "system._Registry.Revive.Update": _RegistryUpdateReviveSystem.abi,
  "system._Registry.Trait.Update": _RegistryUpdateTraitSystem.abi,
  "system._Room.Create": _RoomCreateSystem.abi,
  "system.Leaderboard.Epoch": _SetLeaderboardEpochSystem.abi,
  "system.Account.Move": AccountMoveSystem.abi,
  "system.Account.Register": AccountRegisterSystem.abi,
  "system.Account.Set.Name": AccountSetNameSystem.abi,
  "system.Account.Set.Operator": AccountSetOperatorSystem.abi,
  "system.ERC20.Deposit": ERC20DepositSystem.abi,
  "system.ERC20.Proxy": ERC20ProxySystem.abi,
  "system.ERC20.Withdraw": ERC20WithdrawSystem.abi,
  "system.ERC721.metadata": ERC721MetadataSystem.abi,
  "system.ERC721.Mint": ERC721MintSystem.abi,
  "system.ERC721.Proxy": ERC721ProxySystem.abi,
  "system.ERC721.Stake": ERC721StakeSystem.abi,
  "system.ERC721.Transfer": ERC721TransferSystem.abi,
  "system.ERC721.Unstake": ERC721UnstakeSystem.abi,
  "system.Listing.Buy": ListingBuySystem.abi,
  "system.Listing.Sell": ListingSellSystem.abi,
  "system.Node.Collect": NodeCollectSystem.abi,
  "system.Pet.Feed": PetFeedSystem.abi,
  "system.Pet.Name": PetNameSystem.abi,
  "system.Pet.Revive": PetReviveSystem.abi,
  "system.Pet.SetAccount": PetSetAccountSystem.abi,
  "system.Production.Collect": ProductionCollectSystem.abi,
  "system.Production.Liquidate": ProductionLiquidateSystem.abi,
  "system.Production.Start": ProductionStartSystem.abi,
  "system.Production.Stop": ProductionStopSystem.abi,
  "system.Trade.Accept": TradeAcceptSystem.abi,
  "system.Trade.AddTo": TradeAddToSystem.abi,
  "system.Trade.Cancel": TradeCancelSystem.abi,
  "system.Trade.Confirm": TradeConfirmSystem.abi,
  "system.Trade.Initiate": TradeInitiateSystem.abi,
};
